### ISSUE TITLE
Shairport-sync Development crashes now and then

### ISSUE THREAD

**Issue by th0u** [mikebrady/shairport-sync#1363]
Hello,
I run dev branch of shairport-sync on RPI3 Bullseye.

```
$ shairport-sync -V
4.1-dev-25-ga05db621-AirPlay2-alac-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc`
```

```
$ uname -a
Linux 5.10.63-v7+ #1488 SMP Thu Nov 18 16:14:44 GMT 2021 armv7l GNU/Linux`
```

Today I found that `shairport-sync` was unavailable and I found it crashed. As far as I remember, it wasn't the first time. The previous time I thought I just forgot to enable autostart for the service.

```
Dec  4 22:05:59 raspberry systemd-timesyncd[14583]: Initial synchronization to time server 138.197.153.200:123 (0.debian.pool.ntp.org).
Dec  4 22:07:30 raspberry shairport-sync:      10715.480674075 "rtsp.c:2877" SETUP on Connection 11. Buffered Audio Stream Detected.
Dec  4 22:07:30 raspberry shairport-sync:          0.003984538 "audio_alsa.c:528" alsa: output format chosen is "S32".
Dec  4 22:07:30 raspberry shairport-sync:          0.000192709 "audio_alsa.c:569" alsa: output speed chosen is 44100.
Dec  4 22:07:30 raspberry kernel: [114084.310719] pcm512x 1-004d: No SCLK, using BCLK: -2
Dec  4 22:07:30 raspberry shairport-sync:          0.459361551 "rtp.c:1403" Connection 11: NQPTP new master clock f0b3ec795bb10008.
Dec  4 22:07:30 raspberry shairport-sync:          0.001329273 "player.c:1059" Connection 11: Lead time for first frame 359648745: 0.408032 seconds.
Dec  4 22:07:30 raspberry kernel: [114084.775801] pcm512x 1-004d: No SCLK, using BCLK: -2
Dec  4 22:07:52 raspberry shairport-sync:         22.031718509 "rtsp.c:5017" Connection 12: new connection from 20xx:xxxxx:49210 to self at 20xx:xxxxxxx:7000.
Dec  4 22:07:53 raspberry systemd[1]: shairport-sync.service: Main process exited, code=killed, status=11/SEGV
Dec  4 22:07:53 raspberry systemd[1]: shairport-sync.service: Failed with result 'signal'.
Dec  4 22:07:53 raspberry systemd[1]: shairport-sync.service: Consumed 1h 9min 37.150s CPU time.
```

**Comment by mikebrady** [comment]
Thanks for the post. If you could get it to happen reliably, it would be great. It's not so easy, but it would really help narrow it down.

**Comment by mikebrady** [comment]
Hi there. I fixed a few memory leaks in the latest build. TBH it's unlikely to have fixed this problem, but ya never know...

**Comment by mikebrady** [comment]
See also #1398 -- this may be fixed.

**Comment by bluewalk** [comment]
It actually happens in my Pi Zero 2W as well. Have to restart it multiple times a day.

**Comment by mikebrady** [comment]
Thanks for the report. If you could get it to happen reliably, it would be of great assistance.

**Comment by mikebrady** [comment]
Thanks. Could you let us have the version string, please? You can get it by performing:
```
$ shairport-sync -V
```

**Comment by bluewalk** [comment]
> Thanks. Could you let us have the version string, please? You can get it by performing:
> 
> ```
> $ shairport-sync -V
> ```

Currently running `4.1-dev-168-g18f45202-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc`

**Comment by mikebrady** [comment]
> Just rebuilt with latest sources, now running `4.1-dev-194-gb622c179-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc`. Will keep an eye out.

Excellent, thanks.

**Comment by bluewalk** [comment]
It had been ok for the last few days; then started using it and it quit when the wife wanted to use it after me:

>Feb 20 12:27:57 raspberrypi systemd[1]: shairport-sync.service: Main process exited, code=killed, status=11/SEGV
Feb 20 12:27:57 raspberrypi systemd[1]: shairport-sync.service: Failed with result 'signal'.
Feb 20 12:27:57 raspberrypi systemd[1]: shairport-sync.service: Consumed 1h 3min 18.321s CPU time.

**Comment by bluewalk** [comment]
For now I have set the service to restart automatically as a workaround.

If you @mikebrady require more information (eg debug logs), please let me know, I'd like to help.

**Comment by mikebrady** [comment]
Just FYI another bug was fixed in the last few days -- I don't know if it's relevant, but ya never know... 🙂

**Comment by bluewalk** [comment]
Thanks! Built the latest verison now, keeping an eye on it again 👍 

`4.1-dev-212-gfbcba0de-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc`

**Comment by bluewalk** [comment]
It’s still happening with the same error, anything else I can test to narrow it down?

**Comment by mikebrady** [comment]
Thanks. The very best thing would be to see if there is a quick way of causing it to happen reliably. Then we could mail the issue and fix it.

**Comment by bluewalk** [comment]
It seems to crash after playback, this is what I see in my log last time I used it before the holidays
```
May  1 11:54:48 raspberrypi shairport-sync[1412]: VSX-932: system-power = on
May  1 11:54:48 raspberrypi shairport-sync[1412]: VSX-932: master-volume = 122
May  1 11:54:48 raspberrypi shairport-sync[1412]: VSX-932: SLI01
May  1 12:48:25 raspberrypi shairport-sync: fatal error: audio_alsa: Unable to set hw parameters for device "hw:Device": Protocol error.
```

**Comment by mikebrady** [comment]
Thanks. That looks quite like a hardware problem on the output device -- it seems to be refuseing to accept hardware settings. Is the device a Pioneer VSX-932? If so, it might be worth checking for firmware updates for it.

(BTW, after a fatal error, Shairport Sync will exit.)

**Comment by bluewalk** [comment]
No im using an usb dac, the pioneer stuff is just a command to power it on over the network :)

this is the log from last time, will see if other weird stuff shows up. The logs are different now than before. So just updated to the latest development commit, so let’s see what happens.

**Comment by mikebrady** [comment]
Thanks again.

**Comment by mikebrady** [comment]
>  the pioneer stuff is just a command to power it on over the network :)

Just thinking about this -- it may be that the device needs a little time to settle after power-on before it accepts `alsa` commands.

**Comment by mikebrady** [comment]
Thanks for the clarification. There was some issue that surfaced recently enough in regard to a problem with USB audio on Linux, possibly specifically on Raspberry Pi OS. I'll see if I can find it.

**Comment by mikebrady** [comment]
[This](https://github.com/mikebrady/shairport-sync/issues/1427#issuecomment-1040250153) is the issue I was trying to remember.

**Comment by bluewalk** [comment]
> [This](https://github.com/mikebrady/shairport-sync/issues/1427#issuecomment-1040250153) is the issue I was trying to remember.

Splendid, set `disable_standby_mode` to `always` so let's see what happens. So far so good.
Running `4.1-dev-250-g250704b2-AirPlay2-OpenSSL-Avahi-ALSA-soxr` now

**Comment by bluewalk** [comment]
Still happening, every day I have to restart the service.
Example from yesterday:
```
Aug 20 20:02:22 raspberrypi systemd[1]: shairport-sync.service: Main process exited, code=killed, status=11/SEGV
Aug 20 20:02:22 raspberrypi systemd[1]: shairport-sync.service: Failed with result 'signal'.
```

**Comment by mikebrady** [comment]
Thanks for the update.

**Comment by bluewalk** [comment]
Unfortunately not, it really seems ranndom. I have enabled more logging now so I can provide more information.

**Comment by mikebrady** [comment]
Hi there. We found a Spotify-specific bug that caused Shairport Sync to crash -- see #1551. Specifically, Spotify occasionally omits an important decryption parameter. Now, instead of crashing, Shairport Sync simply stays silent. I wonder if that is the case of the crashes you experienced.

**Comment by bluewalk** [comment]
Great, I will have a look. Now you mention it; it mostly happens when the wife uses spotify to airplay indeed!

**Comment by bluewalk** [comment]
I am running the latest version and it seems to crash less often. If it does it is indeed related to spotify.
Fun fact, a sideloaded spotify doesn't show this behavior.
