### ISSUE TITLE
Lags on airplay2

### ISSUE THREAD

**Issue by Miladnorouzi77** [mikebrady/shairport-sync#1526]
### What happened?

Hi, i'm using airplay2 development branch on RPI 4 , when i'm trying to play music every 2 minutes or 3 minutes music stops about 2 seconds. i'm using bullseye with GUI as my operating system on rpi and i haven't any running task on my rpi.  here is the screenshot of command: sudo shairport-sync --statistics
![Screenshot (119)](https://user-images.githubusercontent.com/32528196/187016526-a5b1e3e4-39f9-433c-867d-444cc4655131.png)
and some times like this:

![Screenshot (121)](https://user-images.githubusercontent.com/32528196/187017068-7a482f27-003e-4665-8b21-29e258a99e00.png)

### Relevant log output
```
0.001511852 "shairport.c:2026" startup in Airplay 2 mode with features 0x405c4a00,0x1c340 on device "dc:a6:32:38:de:25".
         0.000129481 "shairport.c:2069" software version: "4.1-dev-505-g5f92164c-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc"
         0.000021000 "shairport.c:2075" log verbosity is 1.
         0.000049038 "audio_alsa.c:1027" alsa: alsa_maximum_stall_time of 0.200000 sec.
         0.000038870 "audio_alsa.c:1316" alsa: disable_standby_mode is "never".
         0.000017315 "audio_alsa.c:1320" alsa: disable_standby_mode_silence_threshold is 0.040000 seconds.
         0.000017296 "audio_alsa.c:1322" alsa: disable_standby_mode_silence_scan_interval is 0.004000 seconds.
         0.000044593 "audio_alsa.c:1362" alsa: output device name is "default".
         0.000220407 "shairport.c:2104" libsodium initialised.
         0.000332852 "shairport.c:2154" disable resend requests is off.
         0.000024296 "shairport.c:2155" diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
         0.000018278 "shairport.c:2159" statistics_requester status is 0.
         0.000016185 "shairport.c:2164" rtsp listening port is 7000.
         0.000016056 "shairport.c:2165" udp base port is 6001.
         0.000015722 "shairport.c:2166" udp port range is 10.
         0.000015444 "shairport.c:2167" player name is "Cubo".
         0.000015537 "shairport.c:2168" backend is "alsa".
         0.000014389 "shairport.c:2169" run_this_before_play_begins action is "(null)".
         0.000013908 "shairport.c:2170" run_this_after_play_ends action is "(null)".
         0.000016129 "shairport.c:2171" wait-cmd status is 0.
         0.000015537 "shairport.c:2172" run_this_before_play_begins may return output is 0.
         0.000015741 "shairport.c:2173" run_this_if_an_unfixable_error_is_detected action is "(null)".
         0.000016426 "shairport.c:2175" run_this_before_entering_active_state action is  "(null)".
         0.000016056 "shairport.c:2177" run_this_after_exiting_active_state action is  "(null)".
         0.000015166 "shairport.c:2179" active_state_timeout is  10.000000 seconds.
         0.000016408 "shairport.c:2180" mdns backend "(null)".
         0.000013574 "shairport.c:2182" interpolation setting is "auto".
         0.000015389 "shairport.c:2185" interpolation soxr_delay_threshold is 30000000.
         0.000015851 "shairport.c:2186" resync time is 0.050000 seconds.
         0.000016167 "shairport.c:2187" allow a session to be interrupted: 0.
         0.000014278 "shairport.c:2188" busy timeout time is 0.
         0.000014741 "shairport.c:2189" drift tolerance is 0.001995 seconds.
         0.000016148 "shairport.c:2190" password is "(null)".
         0.000013944 "shairport.c:2191" ignore_volume_control is 0.
         0.000014000 "shairport.c:2195" volume_max_db is not set
         0.000013463 "shairport.c:2196" volume range in dB (zero means use the range specified by the mixer): 0.
         0.000016093 "shairport.c:2198" volume_range_combined_hardware_priority (1 means hardware mixer attenuation is used first) is 0.
         0.000016352 "shairport.c:2202" playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
         0.000015907 "shairport.c:2204" disable_synchronization is 0.
         0.000013963 "shairport.c:2205" use_mmap_if_available is 1.
         0.000015111 "shairport.c:2206" output_format automatic selection is enabled.
         0.000016815 "shairport.c:2210" output_rate automatic selection is enabled.
         0.000016407 "shairport.c:2214" audio backend desired buffer length is 0.200000 seconds.
         0.000015093 "shairport.c:2216" audio_backend_buffer_interpolation_threshold_in_seconds is 0.120000 seconds.
         0.000015055 "shairport.c:2218" audio backend latency offset is 0.000000 seconds.
         0.000015963 "shairport.c:2220" audio backend silence lead-in time is "auto".
         0.000015389 "shairport.c:2224" zeroconf regtype is "_raop._tcp".
         0.000015926 "shairport.c:2225" decoders_supported field is 1.
         0.000014260 "shairport.c:2226" use_apple_decoder is 0.
         0.000015055 "shairport.c:2227" alsa_use_hardware_mute is 0.
         0.000015667 "shairport.c:2231" no special mdns service interface was requested.
         0.000031203 "shairport.c:2234" configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
         0.000018241 "shairport.c:2264" loudness is 0.
         0.000015334 "shairport.c:2265" loudness reference level is -20.000000
         0.005525944 "shairport.c:2347" NQPTP is online.
         1.498127499 "shairport.c:250" "soxr" interpolation has been chosen.
```
### Version?

4.1-dev-505-g5f92164c-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks for the report. Can you tell me what sources you were using, e.g. YouTube, Spotify?

**Comment by Miladnorouzi77** [comment]
Hi, Thanks for your reply Mike. The source is Telegram app.

**Comment by mikebrady** [comment]
Okay, thanks. I haven't used Telegram in this way, so pardon my lack of knowledge! Can you explain, please, how to play (?) audio from Telegram. Would it be from a file passed in a conversation, for example?

**Comment by Miladnorouzi77** [comment]
My friend send me a music and its a mp3 file. I've used safari to check if its telegram problem and its really smoother.

**Comment by mikebrady** [comment]
Also, when you're running Shairport Sync from the command line to capture information, it might be helpful to include level `1` verbosity.
```
$ shairport-sync -v --statistics
```
When verbosity is non-zero, more statistical information is displayed. I think it might be helpful in this case.

**Comment by Miladnorouzi77** [comment]
Its the log when music lags:

4.138913276 "player.c:2716" Large negative sync error of -4586 frames (-0.103991 seconds), at frame: 2615238436.
         0.000046870 "player.c:2721" 1675142 frames sent to DAC. DAC buffer contains 3142 frames.
         0.937047851 "player.c:2692" Large positive sync error of 4243 frames (0.096213 seconds), at frame: 2615280676.

**Comment by mikebrady** [comment]
I've tried this with a five-minute MP3 track and the first time I tried it, Telegram (latest version, on fully up-to-date iOS) crashed after about two minutes.
The second time and the third time, it played through to the end. The track was recorded in 128 kbps MP3 format. Here are the logs.

First attempt, where Telegram crashed:
```
Aug 30 10:11:26 RaspberryPi3B shairport-sync[3633]:        224.023810956 "rtsp.c:3100" Connection 1. AP2 Realtime Audio Stream.
Aug 30 10:11:30 RaspberryPi3B shairport-sync[3633]:          3.917421040 "player.c:2649" Connection 1: Playback Started -- AirPlay 2 Realtime.
Aug 30 10:11:38 RaspberryPi3B shairport-sync[3633]:          7.915912810 "player.c:2489" Sync Error ms | Net Sync PPM | All Sync PPM | Missing |   Late | Too Late | Resend Reqs | Min DAC Queue | Min Buffers | Max Buffers | Received FPS | Output FPS (r) | Output FPS (c)
Aug 30 10:11:38 RaspberryPi3B shairport-sync[3633]:          0.000174896 "player.c:2489"          0.73            0.0            0.0         0        9          0             1            7441           220           232       44395.24              N/A              N/A
Aug 30 10:11:46 RaspberryPi3B shairport-sync[3633]:          8.006954111 "player.c:2489"          2.07         -133.1          133.1         0        9          0             1            7554           227           233       44242.45         44099.83         44098.30
Aug 30 10:11:54 RaspberryPi3B shairport-sync[3633]:          8.011025831 "player.c:2489"          2.07         -110.5          110.5         0        9          0             1            7787           228           232       44193.70         44100.04         44098.51
Aug 30 10:12:02 RaspberryPi3B shairport-sync[3633]:          8.008667184 "player.c:2489"          2.01          -56.6           56.6         0        9          0             1            7875           228           232       44152.52         44100.10         44098.57
Aug 30 10:12:10 RaspberryPi3B shairport-sync[3633]:          7.993794632 "player.c:2489"          1.96          -14.2           14.2         0        9          0             1            7846           228           232       44146.26         44100.05         44098.52
Aug 30 10:12:18 RaspberryPi3B shairport-sync[3633]:          8.010919893 "player.c:2489"          1.93            0.0            0.0         0        9          0             1            7546           225           232       44141.94         44100.15         44098.62
Aug 30 10:12:26 RaspberryPi3B shairport-sync[3633]:          8.006089268 "player.c:2489"          1.98          -14.2           14.2         0        9          0             1            7852           228           232       44134.51         44100.04         44098.50
Aug 30 10:12:34 RaspberryPi3B shairport-sync[3633]:          8.010613903 "player.c:2489"          1.97          -11.3           11.3         0        9          0             1            7834           228           232       44132.30         44100.03         44098.50
Aug 30 10:12:42 RaspberryPi3B shairport-sync[3633]:          8.009934737 "player.c:2489"          1.99           -2.8            2.8         0        9          0             1            7785           225           232       44125.99         44100.05         44098.52
Aug 30 10:12:50 RaspberryPi3B shairport-sync[3633]:          7.991596767 "player.c:2489"          1.99           -8.5            8.5         0        9          0             1            7856           228           232       44122.93         44100.03         44098.49
Aug 30 10:12:58 RaspberryPi3B shairport-sync[3633]:          8.010601039 "player.c:2489"          1.96           -5.7            5.7         0        9          0             1            7891           228           232       44122.44         44100.03         44098.49
Aug 30 10:13:06 RaspberryPi3B shairport-sync[3633]:          8.010959580 "player.c:2489"          1.90           -2.8            2.8         0        9          0             1            7811           228           232       44122.25         44100.04         44098.50
Aug 30 10:13:14 RaspberryPi3B shairport-sync[3633]:          8.010672758 "player.c:2489"          1.87            0.0            0.0         0        9          0             1            7818           228           232       44114.57         44100.05         44098.51
Aug 30 10:13:22 RaspberryPi3B shairport-sync[3633]:          8.007062236 "player.c:2489"          1.90            0.0            0.0         0        9          0             1            7826           227           232       44113.00         44100.05         44098.51
Aug 30 10:13:30 RaspberryPi3B shairport-sync[3633]:          7.990705101 "player.c:2489"          1.86            0.0            0.0         0        9          0             1            7866           228           232       44117.79         44100.02         44098.48
Aug 30 10:13:38 RaspberryPi3B shairport-sync[3633]:          8.011100154 "player.c:2489"          1.83            0.0            0.0         0        9          0             1            7874           228           232       44114.78         44100.04         44098.50
Aug 30 10:13:46 RaspberryPi3B shairport-sync[3633]:          8.008830257 "player.c:2489"          1.79            0.0            0.0         0        9          0             1            7822           227           233       44115.55         44100.03         44098.48
Aug 30 10:13:47 RaspberryPi3B shairport-sync[3633]:          1.495479479 "player.c:1643" Connection 1: Playback Stopped. Total playing time 00:02:17. Output: 44100.03 (raw), 44098.48 (corrected) frames per second.
```
Second attempt:
```
Aug 30 10:14:27 RaspberryPi3B shairport-sync[3633]:         39.755503474 "rtsp.c:3100" Connection 1. AP2 Realtime Audio Stream.
Aug 30 10:14:29 RaspberryPi3B shairport-sync[3633]:          1.958732291 "player.c:2649" Connection 1: Playback Started -- AirPlay 2 Realtime.
Aug 30 10:14:37 RaspberryPi3B shairport-sync[3633]:          7.919923695 "player.c:2489" Sync Error ms | Net Sync PPM | All Sync PPM | Missing |   Late | Too Late | Resend Reqs | Min DAC Queue | Min Buffers | Max Buffers | Received FPS | Output FPS (r) | Output FPS (c)
Aug 30 10:14:37 RaspberryPi3B shairport-sync[3633]:          0.000173021 "player.c:2489"          0.37            0.0            0.0         0        0          0             0            7418           222           232       43766.88              N/A              N/A
Aug 30 10:14:45 RaspberryPi3B shairport-sync[3633]:          7.998728694 "player.c:2489"          1.42            0.0            0.0         0        0          0             0            7530           225           232       44108.22         44099.90         44098.32
Aug 30 10:14:53 RaspberryPi3B shairport-sync[3633]:          8.010068799 "player.c:2489"          2.03          -56.6           56.6         0        3          0             1            7558           215           232       44080.51         44099.96         44098.38
Aug 30 10:15:01 RaspberryPi3B shairport-sync[3633]:          7.992282706 "player.c:2489"          1.97          -17.0           17.0         0        3          0             1            7540           225           232       44096.56         44099.99         44098.41
Aug 30 10:15:09 RaspberryPi3B shairport-sync[3633]:          8.007449320 "player.c:2489"          1.97          -14.2           14.2         0        3          0             1            7604           228           232       44103.85         44100.01         44098.43
Aug 30 10:15:17 RaspberryPi3B shairport-sync[3633]:          8.013929476 "player.c:2489"          2.00          -28.3           28.3         0        6          0             2            7606           216           232       44094.33         44100.03         44098.45
Aug 30 10:15:25 RaspberryPi3B shairport-sync[3633]:          8.007053643 "player.c:2489"          1.95          -14.2           14.2         0        6          0             2            7616           226           232       44100.67         44099.96         44098.38
Aug 30 10:15:33 RaspberryPi3B shairport-sync[3633]:          8.010013226 "player.c:2489"          2.00          -31.2           31.2         0        6          0             2            7597           226           232       44097.75         44100.07         44098.48
Aug 30 10:15:41 RaspberryPi3B shairport-sync[3633]:          8.010168590 "player.c:2489"          1.88           -2.8            2.8         0        6          0             2            7589           225           232       44095.11         44099.99         44098.41
Aug 30 10:15:49 RaspberryPi3B shairport-sync[3633]:          7.990610622 "player.c:2489"          1.96           -8.5            8.5         0        6          0             2            7667           226           231       44100.30         44100.03         44098.44
Aug 30 10:15:57 RaspberryPi3B shairport-sync[3633]:          8.024842549 "player.c:2489"          1.98          -31.2           31.2         0       10          0             3            7664           225           232       44102.13         44100.03         44098.45
Aug 30 10:16:05 RaspberryPi3B shairport-sync[3633]:          7.981143695 "player.c:2489"          1.97          -28.3           28.3         0       10          0             3            7512           225           232       44091.14         44100.02         44098.44
Aug 30 10:16:13 RaspberryPi3B shairport-sync[3633]:          8.010728851 "player.c:2489"          1.65            0.0            0.0         0       11          0             4            7476           220           232       44086.33         44100.00         44098.42
Aug 30 10:16:21 RaspberryPi3B shairport-sync[3633]:          8.001573174 "player.c:2489"          1.66           -2.8            2.8         0       14          0             5            7484           212           232       44102.18         44100.03         44098.44
Aug 30 10:16:29 RaspberryPi3B shairport-sync[3633]:          8.011868279 "player.c:2489"          1.99          -39.7           39.7         0       15          0             6            7558           225           232       44099.86         44100.04         44098.45
Aug 30 10:16:37 RaspberryPi3B shairport-sync[3633]:          8.010126351 "player.c:2489"          1.99          -28.3           28.3         0       15          0             6            7510           225           232       44100.69         44100.01         44098.42
Aug 30 10:16:45 RaspberryPi3B shairport-sync[3633]:          8.007877288 "player.c:2489"          1.97          -25.5           25.5         0       18          0             7            7499           212           232       44097.72         44100.02         44098.43
Aug 30 10:16:53 RaspberryPi3B shairport-sync[3633]:          8.010639997 "player.c:2489"          1.99          -39.7           39.7         0       18          0             7            7498           225           232       44098.47         44100.04         44098.45
Aug 30 10:17:01 RaspberryPi3B shairport-sync[3633]:          7.991235883 "player.c:2489"          1.93          -11.3           11.3         0       19          0             8            7572           222           232       44100.86         44100.02         44098.43
Aug 30 10:17:09 RaspberryPi3B shairport-sync[3633]:          8.008529996 "player.c:2489"          1.63            0.0            0.0         0       44          0            20            7480           198           232       44100.00         44100.02         44098.43
Aug 30 10:17:17 RaspberryPi3B shairport-sync[3633]:          8.010152289 "player.c:2489"          2.01          -79.3           79.3         0       44          0            20            7744           227           232       44098.57         44100.02         44098.43
Aug 30 10:17:25 RaspberryPi3B shairport-sync[3633]:          8.010212914 "player.c:2489"          2.01          -48.2           48.2         0       44          0            20            7515           225           232       44099.54         44100.03         44098.44
Aug 30 10:17:33 RaspberryPi3B shairport-sync[3633]:          7.989225205 "player.c:2489"          2.00          -48.2           48.2         0       44          0            20            7926           227           232       44100.15         44100.02         44098.43
Aug 30 10:17:41 RaspberryPi3B shairport-sync[3633]:          8.010786507 "player.c:2489"          1.98          -31.2           31.2         0       44          0            20            7788           227           232       44100.41         44100.02         44098.43
Aug 30 10:17:49 RaspberryPi3B shairport-sync[3633]:          8.009850518 "player.c:2489"          1.95          -14.2           14.2         0       44          0            20            7707           228           232       44097.96         44100.04         44098.44
Aug 30 10:17:57 RaspberryPi3B shairport-sync[3633]:          8.012053643 "player.c:2489"          1.99          -22.7           22.7         0       44          0            20            7874           227           232       44096.70         44100.03         44098.44
Aug 30 10:18:05 RaspberryPi3B shairport-sync[3633]:          7.993320414 "player.c:2489"          1.92           -8.5            8.5         0       44          0            20            7814           228           232       44100.68         44100.02         44098.43
Aug 30 10:18:13 RaspberryPi3B shairport-sync[3633]:          8.004751767 "player.c:2489"          2.01          -28.3           28.3         0       44          0            20            7865           228           232       44101.20         44100.03         44098.44
Aug 30 10:18:21 RaspberryPi3B shairport-sync[3633]:          8.010207966 "player.c:2489"          1.96          -19.8           19.8         0       44          0            20            7554           225           232       44100.13         44100.03         44098.44
Aug 30 10:18:29 RaspberryPi3B shairport-sync[3633]:          8.010877289 "player.c:2489"          1.92           -2.8            2.8         0       44          0            20            7721           225           232       44100.65         44100.02         44098.43
Aug 30 10:18:37 RaspberryPi3B shairport-sync[3633]:          8.009160674 "player.c:2489"          1.98          -25.5           25.5         0       44          0            20            7840           227           232       44100.03         44100.02         44098.43
Aug 30 10:18:45 RaspberryPi3B shairport-sync[3633]:          7.991632757 "player.c:2489"          2.01          -31.2           31.2         0       44          0            20            7903           227           232       44099.93         44100.03         44098.43
Aug 30 10:18:53 RaspberryPi3B shairport-sync[3633]:          8.010269684 "player.c:2489"          1.95          -25.5           25.5         0       44          0            20            7737           225           232       44100.32         44100.02         44098.43
Aug 30 10:19:01 RaspberryPi3B shairport-sync[3633]:          8.007975362 "player.c:2489"          1.90            0.0            0.0         0       44          0            20            7808           228           232       44101.26         44100.02         44098.42
Aug 30 10:19:09 RaspberryPi3B shairport-sync[3633]:          8.009832809 "player.c:2489"          2.00          -39.7           39.7         0       44          0            20            7903           228           232       44098.25         44100.03         44098.43
Aug 30 10:19:17 RaspberryPi3B shairport-sync[3633]:          8.010657862 "player.c:2489"          1.96          -19.8           19.8         0       44          0            20            7889           227           232       44099.82         44100.02         44098.42
Aug 30 10:19:25 RaspberryPi3B shairport-sync[3633]:          7.987935153 "player.c:2489"          1.99          -31.2           31.2         0       44          0            20            7845           228           232       44101.60         44100.02         44098.42
Aug 30 10:19:33 RaspberryPi3B shairport-sync[3633]:          8.010036976 "player.c:2489"          1.86          -22.7           22.7         0       44          0            20            7648           227           232       44100.93         44100.03         44098.43
Aug 30 10:19:40 RaspberryPi3B shairport-sync[3633]:          6.570731456 "player.c:1643" Connection 1: Playback Stopped. Total playing time 00:05:10. Output: 44100.03 (raw), 44098.43 (corrected) frames per second.
```
Third attempt:
```
Aug 30 10:19:58 RaspberryPi3B shairport-sync[3633]:         18.710364680 "rtsp.c:3100" Connection 1. AP2 Realtime Audio Stream.
Aug 30 10:20:02 RaspberryPi3B shairport-sync[3633]:          3.915325416 "player.c:2649" Connection 1: Playback Started -- AirPlay 2 Realtime.
Aug 30 10:20:10 RaspberryPi3B shairport-sync[3633]:          7.918588903 "player.c:2489" Sync Error ms | Net Sync PPM | All Sync PPM | Missing |   Late | Too Late | Resend Reqs | Min DAC Queue | Min Buffers | Max Buffers | Received FPS | Output FPS (r) | Output FPS (c)
Aug 30 10:20:10 RaspberryPi3B shairport-sync[3633]:          0.000169583 "player.c:2489"          0.27            0.0            0.0         0        0          0             0            7426           221           232       44077.90              N/A              N/A
Aug 30 10:20:18 RaspberryPi3B shairport-sync[3633]:          8.020307445 "player.c:2489"          0.34            0.0            0.0         0        0          0             0            7433           224           232       44120.36         44099.98         44098.37
Aug 30 10:20:26 RaspberryPi3B shairport-sync[3633]:          7.987397341 "player.c:2489"          0.94            0.0            0.0         0        5          0             2            7505           212           232       44136.02         44099.99         44098.38
Aug 30 10:20:34 RaspberryPi3B shairport-sync[3633]:          8.004179945 "player.c:2489"          0.94            0.0            0.0         0       11          0             6            7501           203           232       44091.90         44100.14         44098.53
Aug 30 10:20:42 RaspberryPi3B shairport-sync[3633]:          8.015461247 "player.c:2489"          1.44            0.0            0.0         0       11          0             6            7589           226           232       44119.52         44100.04         44098.42
Aug 30 10:20:50 RaspberryPi3B shairport-sync[3633]:          8.010403538 "player.c:2489"          1.77            0.0            0.0         0       11          0             6            7697           225           232       44111.70         44100.06         44098.44
Aug 30 10:20:58 RaspberryPi3B shairport-sync[3633]:          7.990716091 "player.c:2489"          1.97          -17.0           17.0         0       13          0             7            7497           216           232       44110.98         44100.08         44098.46
Aug 30 10:21:06 RaspberryPi3B shairport-sync[3633]:          8.008228174 "player.c:2489"          1.90          -14.2           14.2         0       55          0            37            7402           201           232       44107.08         44100.02         44098.41
Aug 30 10:21:14 RaspberryPi3B shairport-sync[3633]:          8.010312393 "player.c:2489"          1.74            0.0            0.0         0       69          0            44            7498           212           232       44112.83         44100.04         44098.42
Aug 30 10:21:22 RaspberryPi3B shairport-sync[3633]:          8.010949528 "player.c:2489"          1.90           -2.8            2.8         0       72          0            45            7537           217           232       44108.60         44100.05         44098.43
Aug 30 10:21:30 RaspberryPi3B shairport-sync[3633]:          7.992805101 "player.c:2489"          2.02          -51.0           51.0         0       76          0            48            7508           208           232       44109.28         44100.07         44098.45
Aug 30 10:21:38 RaspberryPi3B shairport-sync[3633]:          8.004794945 "player.c:2489"          1.95          -22.7           22.7         0       87          0            53            7533           211           232       44106.72         44100.07         44098.45
Aug 30 10:21:46 RaspberryPi3B shairport-sync[3633]:          8.021691924 "player.c:2489"          1.93           -5.7            5.7         0       87          0            53            7497           218           232       44107.30         44100.05         44098.43
Aug 30 10:21:54 RaspberryPi3B shairport-sync[3633]:          7.999605361 "player.c:2489"          1.89            0.0            0.0         0       87          0            53            7493           217           232       44107.83         44100.06         44098.44
Aug 30 10:22:02 RaspberryPi3B shairport-sync[3633]:          8.010056612 "player.c:2489"          2.04          -70.8           70.8         0       87          0            53            7549           225           232       44105.70         44100.06         44098.44
Aug 30 10:22:10 RaspberryPi3B shairport-sync[3633]:          7.991045830 "player.c:2489"          2.00          -22.7           22.7         0       87          0            53            7524           226           231       44105.31         44100.06         44098.44
Aug 30 10:22:18 RaspberryPi3B shairport-sync[3633]:          8.010168018 "player.c:2489"          1.97          -19.8           19.8         0       87          0            53            7496           225           232       44106.18         44100.04         44098.42
Aug 30 10:22:26 RaspberryPi3B shairport-sync[3633]:          8.008536403 "player.c:2489"          2.01          -56.6           56.6         0       90          0            54            7504           212           232       44107.12         44100.04         44098.42
Aug 30 10:22:34 RaspberryPi3B shairport-sync[3633]:          8.000647966 "player.c:2489"          1.95           -5.7            5.7         0       94          0            56            7557           212           232       44101.99         44100.06         44098.44
Aug 30 10:22:42 RaspberryPi3B shairport-sync[3633]:          8.020821924 "player.c:2489"          1.93           -5.7            5.7         0       94          0            56            7630           225           232       44103.65         44100.04         44098.42
Aug 30 10:22:50 RaspberryPi3B shairport-sync[3633]:          7.990593278 "player.c:2489"          1.97          -17.0           17.0         0       94          0            56            7705           226           232       44105.80         44100.03         44098.41
Aug 30 10:22:58 RaspberryPi3B shairport-sync[3633]:          8.007788330 "player.c:2489"          1.96           -8.5            8.5         0       94          0            56            7548           225           232       44101.13         44100.04         44098.42
Aug 30 10:23:06 RaspberryPi3B shairport-sync[3633]:          8.010909685 "player.c:2489"          2.01          -34.0           34.0         0       94          0            56            7604           224           232       44105.13         44100.05         44098.43
Aug 30 10:23:14 RaspberryPi3B shairport-sync[3633]:          8.012278643 "player.c:2489"          2.00          -31.2           31.2         0       94          0            56            7655           225           232       44101.81         44100.04         44098.42
Aug 30 10:23:22 RaspberryPi3B shairport-sync[3633]:          8.008105465 "player.c:2489"          1.86           -5.7            5.7         0       97          0            57            7487           216           232       44102.77         44100.05         44098.43
Aug 30 10:23:30 RaspberryPi3B shairport-sync[3633]:          7.989466508 "player.c:2489"          1.95          -11.3           11.3         0       98          0            58            7499           225           232       44104.68         44100.05         44098.43
Aug 30 10:23:38 RaspberryPi3B shairport-sync[3633]:          8.007270830 "player.c:2489"          1.87          -14.2           14.2         0       98          0            58            7490           221           232       44090.82         44100.05         44098.42
Aug 30 10:23:46 RaspberryPi3B shairport-sync[3633]:          8.014059007 "player.c:2489"          1.48            0.0            0.0         0       98          0            58            7460           221           232       44103.78         44100.04         44098.42
Aug 30 10:23:54 RaspberryPi3B shairport-sync[3633]:          8.009112341 "player.c:2489"          1.98          -39.7           39.7         0       98          0            58            7512           225           232       44101.69         44100.03         44098.41
Aug 30 10:24:02 RaspberryPi3B shairport-sync[3633]:          7.989902862 "player.c:2489"          2.04          -59.5           59.5         0       98          0            58            7498           225           232       44104.58         44100.04         44098.41
Aug 30 10:24:10 RaspberryPi3B shairport-sync[3633]:          8.010007653 "player.c:2489"          1.98          -31.2           31.2         0       98          0            58            7735           225           232       44103.48         44100.05         44098.43
Aug 30 10:24:18 RaspberryPi3B shairport-sync[3633]:          8.010345153 "player.c:2489"          1.90           -5.7            5.7         0       99          0            59            7512           216           232       44103.97         44100.04         44098.42
Aug 30 10:24:26 RaspberryPi3B shairport-sync[3633]:          8.002669007 "player.c:2489"          1.97          -22.7           22.7         0       99          0            59            7496           225           231       44102.75         44100.04         44098.41
Aug 30 10:24:34 RaspberryPi3B shairport-sync[3633]:          8.016876351 "player.c:2489"          2.03          -48.2           48.2         0      102          0            60            7631           212           231       44102.44         44100.05         44098.42
Aug 30 10:24:42 RaspberryPi3B shairport-sync[3633]:          7.990542341 "player.c:2489"          2.00          -34.0           34.0         0      102          0            60            7541           212           232       44103.71         44100.04         44098.42
Aug 30 10:24:50 RaspberryPi3B shairport-sync[3633]:          8.012456351 "player.c:2489"          1.88            0.0            0.0         0      102          0            60            7513           225           232       44098.73         44100.05         44098.42
Aug 30 10:24:58 RaspberryPi3B shairport-sync[3633]:          7.999959320 "player.c:2489"          1.60            0.0            0.0         0      102          0            60            7481           221           233       44100.99         44100.04         44098.41
Aug 30 10:25:06 RaspberryPi3B shairport-sync[3633]:          8.015463903 "player.c:2489"          1.32            0.0            0.0         0      102          0            60            7473           224           233       44104.10         44100.04         44098.42
Aug 30 10:25:07 RaspberryPi3B shairport-sync[3633]:          0.302009011 "player.c:1643" Connection 1: Playback Stopped. Total playing time 00:05:04. Output: 44100.04 (raw), 44098.42 (corrected) frames per second.
```
Given that Telegram crashed, my guess is that the issue is a fault in Telegram.

**Comment by mikebrady** [comment]
Aha, I may have spoken too soon. Please see [this issue](https://github.com/mikebrady/shairport-sync/issues/1515). A fix has been pushed into the `development` branch. If you got a chance to try it and report back, it would be appreciated.

**Comment by Miladnorouzi77** [comment]
Hey Mike, Sure. I will update and share it with you.

**Comment by Miladnorouzi77** [comment]
I tested the new version on development branch, problem not fixed and its more unstable now :(
![Screenshot (124)](https://user-images.githubusercontent.com/32528196/187721188-22f7662f-e2e2-4629-868a-0b9eaaa6b6fa.png)

**Comment by mikebrady** [comment]
Wah!

**Comment by mikebrady** [comment]
So, just looking at the logs above, lots of packets are missing, indicating a poor quality network. For reference, here are some logs from this system.

The first is from YouTube on a MacBook Pro M1 to Shairport Sync on a Pi 3. Both are connected over WiFi (a Unifi AC-Pro) and are fully up to date.
```
Connection 1: Playback Started -- AirPlay 2 Realtime.
Sync Error ms | Net Sync PPM | All Sync PPM | Missing | Resend Reqs | Output FPS (r) | Output FPS (c)
         0.45            0.0            0.0         0             0              N/A              N/A
         1.07            0.0            0.0         0             0         44100.11         44076.11
         1.24            0.0            0.0         0             0         44100.08         44078.58
         1.35            0.0            0.0         0             0         44100.11         44080.44
         1.41            0.0            0.0         0             0         44100.10         44081.79
         1.42            0.0            0.0         0             0         44100.02         44085.62
         1.48            0.0            0.0         0             0         44100.04         44089.51
         1.48            0.0            0.0         0             0         44100.04         44091.70
         1.48            0.0            0.0         0             0         44100.03         44092.95
         1.38            0.0            0.0         0             0         44100.04         44093.68
         1.46            0.0            0.0         0             0         44100.04         44094.07
         1.51            0.0            0.0         0             0         44100.02         44094.25
         1.43            0.0            0.0         0             0         44100.04         44094.33
         1.46            0.0            0.0         0             0         44100.13         44094.41
         1.49            0.0            0.0         0             0         44100.03         44094.26
         1.44            0.0            0.0         0             0         44100.03         44094.17
         1.32            0.0            0.0         0             0         44100.05         44094.10
         1.26            0.0            0.0         0             0         44100.03         44093.98
         1.03            0.0            0.0         0             0         44100.02         44093.86
         1.21            0.0            0.0         0             0         44100.04         44093.77
Connection 1: Playback Stopped. Total playing time 00:02:46. Output: 44100.04 (raw), 44093.77 (corrected) frames per second.
```
You can see, in particular, there are no missing packets, and no resend requests.

The second log from an iPhone XS Pro Max to the same Pi 3, on the same WiFi network and all fully up to date. There are three apps. The first is YouTube. As you can see, no missing packets, no resend requests.
The second is Telegram playing that MP3 file -- lots and lots (too many) resend requests, but zero missing packets.
The third is Spotify -- small numbers of resend requests, zero missing packets.

```
<YouTube>
Connection 3: Playback Started -- AirPlay 2 Realtime.
Sync Error ms | Net Sync PPM | All Sync PPM | Missing | Resend Reqs | Output FPS (r) | Output FPS (c)
        -0.51            0.0            0.0         0             0              N/A              N/A
        -1.12            2.8            2.8         0             0         44100.27         44100.65
        -1.25            0.0            0.0         0             0         44100.12         44100.34
        -1.27            0.0            0.0         0             0         44100.05         44100.11
        -0.87            0.0            0.0         0             0         44100.13         44100.04
        -0.49            0.0            0.0         0             0         44100.04         44099.80
        -0.26            0.0            0.0         0             0         44100.04         44099.66
        -0.05            0.0            0.0         0             0         44100.09         44099.58
        -0.15            0.0            0.0         0             0         44100.07         44099.42
        -0.69            0.0            0.0         0             0         44100.05         44099.28
        -0.83            0.0            0.0         0             0         44100.08         44099.19
Connection 3: Playback Stopped. Total playing time 00:01:29. Output: 44100.08 (raw), 44099.19 (corrected) frames per second.
<Telegram>
Connection 3: Playback Started -- AirPlay 2 Realtime.
Sync Error ms | Net Sync PPM | All Sync PPM | Missing | Resend Reqs | Output FPS (r) | Output FPS (c)
         0.37            0.0            0.0         0            57              N/A              N/A
         0.80            0.0            0.0         0            80         44099.89         44097.06
         0.90            0.0            0.0         0            94         44100.03         44097.13
         1.43            0.0            0.0         0           106         44099.99         44097.02
         2.10         -155.8          155.8         0           107         44100.02         44096.99
         2.04          -51.0           51.0         0           109         44100.00         44096.91
         2.01          -34.0           34.0         0           116         44099.98         44096.83
         2.00          -25.5           25.5         0           122         44099.98         44096.78
         1.56            0.0            0.0         0           131         44100.02         44096.76
         1.41            0.0            0.0         0           134         44100.00         44096.70
         1.89           -5.7            5.7         0           142         44100.00         44096.65
         2.04          -51.0           51.0         0           145         44100.04         44096.63
         2.00          -22.7           22.7         0           150         44100.02         44096.57
         2.02          -39.7           39.7         0           156         44100.02         44096.52
         1.96          -11.3           11.3         0           160         44100.03         44096.49
         2.02          -34.0           34.0         0           168         44100.03         44096.45
         1.98          -19.8           19.8         0           171         44100.01         44096.40
         1.98          -14.2           14.2         0           185         44100.02         44096.37
         2.01          -36.8           36.8         0           208         44100.01         44096.33
         1.86            0.0            0.0         0           224         44100.03         44096.31
         1.99          -31.2           31.2         0           229         44100.03         44096.27
         1.96          -14.2           14.2         0           240         44100.03         44096.24
         1.77            0.0            0.0         0           246         44100.04         44096.22
         1.80           -5.7            5.7         0           250         44100.04         44096.19
         2.01          -31.2           31.2         0           260         44100.04         44096.16
         1.79            0.0            0.0         0           266         44100.02         44096.12
         1.61            0.0            0.0         0           283         44100.02         44096.09
         1.80            0.0            0.0         0           299         44100.02         44096.06
         2.02          -65.1           65.1         0           310         44100.03         44096.05
         2.04          -96.3           96.3         0           311         44100.03         44096.02
         2.03          -48.2           48.2         0           311         44100.03         44096.00
         2.03          -42.5           42.5         0           311         44100.03         44095.98
         2.00          -22.7           22.7         0           311         44100.03         44095.95
         1.97          -22.7           22.7         0           314         44100.03         44095.93
         1.73            0.0            0.0         0           314         44100.03         44095.91
         1.23            0.0            0.0         0           314         44100.03         44095.89
         0.93            0.0            0.0         0           314         44100.03         44095.88
         1.03            0.0            0.0         0           314         44100.03         44095.86
Connection 3: Playback Stopped. Total playing time 00:05:11. Output: 44100.03 (raw), 44095.86 (corrected) frames per second.
<Spotify>
Connection 3: Playback Started -- AirPlay 2 Realtime.
Sync Error ms | Net Sync PPM | All Sync PPM | Missing | Resend Reqs | Output FPS (r) | Output FPS (c)
         0.40            0.0            0.0         0             0              N/A              N/A
         1.12            0.0            0.0         0             0         44100.31         44111.93
         1.77          -19.8           19.8         0             0         44100.00         44111.21
         2.01          -48.2           48.2         0             0         44100.09         44110.91
         1.98          -22.7           22.7         0             1         44100.05         44110.48
         2.03          -59.5           59.5         0             1         44100.05         44110.12
         2.00          -39.7           39.7         0             1         44100.08         44109.80
         1.98          -28.3           28.3         0             1         44100.03         44109.42
         1.98          -28.3           28.3         0             1         44100.04         44109.10
         1.97          -28.3           28.3         0             1         44100.06         44108.81
         1.98          -11.3           11.3         0             1         44100.02         44108.48
         1.99          -28.3           28.3         0             1         44100.02         44108.19
         1.97          -28.3           28.3         0             1         44100.04         44107.94
         1.78            0.0            0.0         0             1         44100.03         44107.66
         1.91          -14.2           14.2         0             1         44100.05         44107.42
         2.00          -25.5           25.5         0             1         44100.03         44107.16
         1.98          -28.3           28.3         0             1         44100.03         44106.92
         1.95          -11.3           11.3         0             1         44100.07         44106.74
         1.96          -14.2           14.2         0             1         44100.03         44106.48
         1.98          -34.0           34.0         0             1         44100.05         44106.29
         1.86            0.0            0.0         0             1         44100.05         44106.08
         1.99          -25.5           25.5         0             1         44100.04         44105.88
         2.00          -31.2           31.2         0             1         44100.05         44105.71
         1.97           -8.5            8.5         0             1         44100.04         44105.51
         1.99          -25.5           25.5         0             1         44100.04         44105.34
         1.99          -22.7           22.7         0             1         44100.05         44105.18
         1.98          -31.2           31.2         0             1         44100.05         44105.01
         1.98           -8.5            8.5         0             1         44100.05         44104.86
         1.98           -8.5            8.5         0             1         44100.04         44104.70
         2.02          -22.7           22.7         0             1         44100.04         44104.55
         1.92          -11.3           11.3         0             1         44100.05         44104.42
         2.00          -31.2           31.2         0             1         44100.04         44104.27
Connection 3: Playback Stopped. Total playing time 00:04:16. Output: 44100.04 (raw), 44104.27 (corrected) frames per second.
```
Set against these logs, your logs portray a very poor network situation. It's not possible to tell whether it is the local network or the internet, but it is really a bad story, with thousands of missing packets and hundreds of resend requests. If you turn on one level of verbosity, the minimum and maximum number of waiting packets, each occupying one "buffer") will be included, and this might give us an idea whether the internet connection is the problem or not. Here is an example using Spotify on the iPhone:
```
       10.599503173 "rtsp.c:3103" Connection 1. AP2 Realtime Audio Stream.
         1.903480677 "player.c:2649" Connection 1: Playback Started -- AirPlay 2 Realtime.
         7.923227757 "player.c:2489" Sync Error ms | Net Sync PPM | All Sync PPM | Missing |   Late | Too Late | Resend Reqs | Min DAC Queue | Min Buffers | Max Buffers | Received FPS | Output FPS (r) | Output FPS (c)
         0.000146615 "player.c:2489"         -0.24            2.9            2.9         0        0          0             0            7400           216           232       44620.56              N/A              N/A
         8.005824319 "player.c:2489"         -0.65            0.0            0.0         0        0          0             0            7369           206           232       44340.03         44099.95         44098.09
         8.018155883 "player.c:2489"         -0.59            0.0            0.0         0        0          0             0            7385           211           232       44240.79         44100.19         44098.33
         8.004678174 "player.c:2489"         -1.74           39.7           39.7         0        0          0             0            7319           216           232       44194.88         44100.04         44098.19
         8.008856351 "player.c:2489"         -1.44            0.0            0.0         0        0          0             0            7355           216           232       44170.93         44100.08         44098.22
         7.989743695 "player.c:2489"         -0.94            0.0            0.0         0        0          0             0            7339           215           232       44173.99         44100.06         44098.20
         8.009906038 "player.c:2489"          0.16            0.0            0.0         0        0          0             0            7595           227           232       44159.62         44100.04         44098.17
         8.020178487 "player.c:2489"          0.19            0.0            0.0         0        9          0             1            7411           221           232       44154.22         44100.07         44098.20
         7.998608174 "player.c:2489"         -0.09            0.0            0.0         0        9          0             1            7411           221           232       44141.43         44100.05         44098.19
         8.010179736 "player.c:2489"          0.77            0.0            0.0         0        9          0             1            7567           225           232       44134.68         44100.06         44098.19
         7.990952758 "player.c:2489"          0.90            0.0            0.0         0        9          0             1            7543           224           232       44131.67         44100.04         44098.17
         8.011035622 "player.c:2489"          0.45            0.0            0.0         0       10          0             2            7439           225           232       44133.26         44100.05         44098.18
         8.008546143 "player.c:2489"          0.12            0.0            0.0         0       10          0             2            7415           213           232       44132.46         44100.04         44098.17
         7.997847340 "player.c:2489"         -0.50            0.0            0.0         0       13          0             3            7383           209           233       44126.89         44100.03         44098.16
         8.022363591 "player.c:2489"          0.02            0.0            0.0         0       13          0             3            7427           225           232       44124.83         44100.04         44098.17
         7.989012184 "player.c:2489"         -0.14            0.0            0.0         0       13          0             3            7407           207           232       44121.72         44100.04         44098.17
         8.011741456 "player.c:2489"          0.54            0.0            0.0         0       16          0             4            7415           216           232       44125.79         44100.05         44098.18
         8.011739997 "player.c:2489"          0.81            0.0            0.0         0       16          0             4            7503           222           232       44122.68         44100.04         44098.16
         8.006678069 "player.c:2489"          1.83          -14.2           14.2         0       16          0             4            7515           225           232       44120.72         44100.05         44098.17
         7.998927445 "player.c:2489"          1.92          -11.3           11.3         0       16          0             4            7542           225           232       44119.71         44100.04         44098.16
         8.001518851 "player.c:2489"          1.91           -2.8            2.8         0       19          0             5            7506           212           232       44119.86         44100.04         44098.16
         8.011031820 "player.c:2489"          2.01          -62.3           62.3         0       19          0             5            7497           225           232       44119.36         44100.05         44098.17
         8.008866820 "player.c:2489"          2.01          -45.3           45.3         0       19          0             5            7522           224           232       44117.77         44100.03         44098.15
         7.995575987 "player.c:2489"          1.98          -14.2           14.2         0       19          0             5            7518           225           232       44115.94         44100.05         44098.17
         8.004349528 "player.c:2489"          1.96          -11.3           11.3         0       19          0             5            7742           226           232       44117.39         44100.05         44098.16
         8.010832549 "player.c:2489"          1.82            0.0            0.0         0       19          0             5            7590           226           232       44117.12         44100.04         44098.15
         8.008690309 "player.c:2489"          1.92           -5.7            5.7         0       24          0             6            7540           212           232       44112.81         44100.04         44098.15
         8.011539841 "player.c:2489"          2.01          -42.5           42.5         0       24          0             6            7605           212           232       44112.80         44100.03         44098.15
         7.988702757 "player.c:2489"          1.79           -2.8            2.8         0       36          0             8            7492           212           232       44115.63         44100.04         44098.15
         8.010674685 "player.c:2489"          1.85          -17.0           17.0         0       39          0             9            7502           216           232       44114.01         44100.05         44098.16
         8.012196768 "player.c:2489"          1.34            0.0            0.0         0       39          0             9            7474           221           232       44113.83         44100.04         44098.15
         8.009908799 "player.c:2489"          1.70           -5.7            5.7         0       39          0             9            7510           212           232       44114.07         44100.05         44098.16
         8.009864684 "player.c:2489"          2.03          -59.5           59.5         0       39          0             9            7595           225           232       44111.62         44100.03         44098.15
         7.989272445 "player.c:2489"          1.96          -25.5           25.5         0       39          0             9            7552           225           232       44112.84         44100.04         44098.15
         8.009903799 "player.c:2489"          1.99          -34.0           34.0         0       39          0             9            7510           225           232       44112.92         44100.03         44098.14
         8.009772341 "player.c:2489"          1.98          -25.5           25.5         0       39          0             9            7556           225           232       44110.72         44100.04         44098.15
         8.010992809 "player.c:2489"          2.00          -34.0           34.0         0       39          0             9            7557           225           232       44110.87         44100.05         44098.16
         7.990000830 "player.c:2489"          1.97            0.0            0.0         0       39          0             9            7541           225           232       44111.88         44100.03         44098.14
         8.008679945 "player.c:2489"          2.00          -28.3           28.3         0       42          0            10            7545           216           232       44110.99         44100.04         44098.15
         8.010539633 "player.c:2489"          1.98          -22.7           22.7         0       42          0            10            7591           225           232       44111.16         44100.03         44098.14
         8.009252965 "player.c:2489"          1.97          -17.0           17.0         0       42          0            10            7603           221           232       44109.50         44100.03         44098.14
         7.996437810 "player.c:2489"          2.00          -34.0           34.0         0       54          0            11            7545           216           232       44110.39         44100.04         44098.14
         2.132633593 "player.c:1643" Connection 1: Playback Stopped. Total playing time 00:05:40. Output: 44100.04 (raw), 44098.14 (corrected) frames per second.
```
Th minimum number of buffers does not fall below around 215, indicating that packets are arriving in good time.

**Comment by Miladnorouzi77** [comment]
thanks for your response Mike. I will check with verbosity level 1 and share it here.

**Comment by Miladnorouzi77** [comment]
### Sync Error ms | Net Sync PPM | All Sync PPM | Missing | Resend Reqs | Output FPS (r) | Output FPS (c)
        -0.06            0.0            0.0         0             0              N/A              N/A
        -0.26            0.0            0.0         0             0         44101.48         44098.80
        -0.46            0.0            0.0         0             0         44099.78         44097.12
        -0.49            0.0            0.0         0             0         44099.86         44097.21
        -0.44            0.0            0.0         0             0         44099.83         44097.20
        -0.52            0.0            0.0         0             3         44099.87         44097.26
        -0.67            0.0            0.0         0             3         44099.88         44097.28
        -0.64            0.0            0.0         0             3         44099.88         44097.30
        -0.77            0.0            0.0         0             3         44099.86         44097.30
        -0.88            0.0            0.0         0             3         44099.88         44097.33
        -2.38          832.7          855.4         0             5              N/A              N/A
         0.37            0.0            0.0         0             5         44099.81         44097.46
         0.28            0.0            0.0         0             8         44099.85         44097.51


The problem is that missing is 0 but the output FPS is N\A and music stops for about 2 seconds and in the new update maybe more. All songs are downloaded so the all casting locally, how can i check that is that the router fault?

**Comment by Miladnorouzi77** [comment]
### Sync Error ms | Net Sync PPM | All Sync PPM | Missing | Resend Reqs | Output FPS (r) | Output FPS (c)
        -0.06            0.0            0.0         0             0              N/A              N/A
        -0.26            0.0            0.0         0             0         44101.48         44098.80
        -0.46            0.0            0.0         0             0         44099.78         44097.12
        -0.49            0.0            0.0         0             0         44099.86         44097.21
        -0.44            0.0            0.0         0             0         44099.83         44097.20
        -0.52            0.0            0.0         0             3         44099.87         44097.26
        -0.67            0.0            0.0         0             3         44099.88         44097.28
        -0.64            0.0            0.0         0             3         44099.88         44097.30
        -0.77            0.0            0.0         0             3         44099.86         44097.30
        -0.88            0.0            0.0         0             3         44099.88         44097.33
        -2.38          832.7          855.4         0             5              N/A              N/A
         0.37            0.0            0.0         0             5         44099.81         44097.46
         0.28            0.0            0.0         0             8         44099.85         44097.51
         0.10            0.0            0.0         0             8         44099.82         44097.50
        -0.12            0.0            0.0         0             8         44099.86         44097.56
        -0.22            0.0            0.0         0             8         44099.84         44097.55
        -0.40            0.0            0.0         0             8         44099.86         44097.59
        -0.48           48.2          308.7         0             8              N/A              N/A
        26.60        -1373.7         1373.7         0             8         44099.86         44097.72
        22.15        -1175.5         1390.7        25            16              N/A              N/A
        -0.62            0.0            0.0        25            16         44100.13         44098.05
        -0.88            0.0            0.0        25            16         44099.97         44097.91
        -0.70            0.0            0.0        25            16         44099.89         44097.84
        -1.01            0.0            0.0        25            16         44099.86         44097.82
        -1.08            0.0            0.0        25            16         44099.88         44097.86
        -1.49            0.0            0.0        25            16         44099.89         44097.88
        -1.65            0.0            0.0        25            17         44099.88         44097.88
        -1.75            0.0            0.0        25            17         44099.88         44097.89
        -1.71            0.0            0.0        25            17         44099.87         44097.89
        -1.84            0.0            0.0        25            17         44099.88         44097.91
        -1.72            0.0            0.0        25            17         44099.88         44097.93
        -1.62            0.0            0.0        25            17         44099.87         44097.93
        -1.64            0.0            0.0        25            17         44099.88         44097.94
        -1.92           19.8           19.8        25            17         44099.87         44097.95
        -2.00           36.8           36.8        25            21         44099.88         44097.97
        -1.76            2.8            2.8        25            21         44099.89         44097.99
        -1.41            0.0            0.0        25            21         44099.88         44097.99
        -1.54            0.0            0.0        25            21         44099.87         44098.00
        -1.62            0.0            0.0        25            21         44099.88         44098.01
        -1.66            2.8            2.8        25            21         44099.88         44098.02
        -1.59            0.0            0.0        25            21         44099.88         44098.03
        -1.72            0.0            0.0        25            21         44099.88         44098.04
        -1.88            0.0            0.0        25            21         44099.88         44098.05
        -1.89            0.0            0.0        25            21         44099.88         44098.06
        -1.95            2.8            2.8        25            21         44099.88         44098.07
        -1.96           11.3           11.3        25            21         44099.88         44098.08
        -1.89            0.0            0.0        25            21         44099.88         44098.10
        -1.91            5.7            5.7        25            21         44099.87         44098.10
        -1.87            0.0            0.0        25            21         44099.88         44098.11
         1.68         -351.2          861.1        25            23              N/A              N/A
        -0.70            0.0            0.0        25            23         44099.99         44098.52
        -0.36            0.0            0.0        25            23         44099.89         44098.43
        -0.63            0.0            0.0        25            23         44099.91         44098.46
        -0.82            0.0            0.0        25            23         44099.91         44098.47
        -1.02            0.0            0.0        25            23         44099.88         44098.45
        -1.18            0.0            0.0        25            23         44099.87         44098.44
        -1.27            0.0            0.0        25            26         44099.87         44098.45
        -1.42            0.0            0.0        25            26         44099.89         44098.47
        -1.45            0.0            0.0        25            26         44099.89         44098.48
        -1.48            0.0            0.0        25            26         44099.88         44098.48
        -1.54            0.0            0.0        25            26         44099.87         44098.48
        -1.62            0.0            0.0        25            26         44099.87         44098.49
        -1.67            0.0            0.0        25            26         44099.88         44098.50
        -1.75            0.0            0.0        25            28         44099.88         44098.51
        -1.72            0.0            0.0        25            29         44099.88         44098.51
        -1.74            0.0            0.0        25            29         44099.88         44098.52
        -1.73            2.8            2.8        25            29         44099.88         44098.53
        -1.63            0.0            0.0        25            29         44099.87         44098.53
        -1.78            2.8            2.8        25            29         44099.87         44098.53

Now there is missing packets too.

**Comment by mikebrady** [comment]
Thanks for those logs. The `N/A` (i.e. Not Available) entries are probably because there were no packets to play, so, if anything, it's worse than it looks.

There are a few small suggestions about networking in [TROUBLESHOOTING.md](https://github.com/mikebrady/shairport-sync/blob/development/TROUBLESHOOTING.md), but otherwise you'll have to debug your network situation yourself -- it's not a Shairport-Sync-specific thing.

**Comment by ErikFontanel** [comment]
I'm experiencing the same problem with the Airplay 2 development branch on a RPi 3 (Dietpi Bullseye) while streaming audio with Airfoil from my M1 Macbook Pro. I'm using NQPTP and the default configuration except for `audio_backend_buffer_desired_length_in_seconds = 0.8;`.  My Shairport Sync version is `4.1-dev-519-g6767bde9-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc`. Sometimes the RPi completely chokes up after I kill the Airplay connection from the server.

I also have a RPi Zero W in another room running almost the same setup without issues, NQPTP `7e3c2b79f3c0540e2e` and Shairport Sync version `4.1-dev-163-g7212504c-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc`. 

I don't suspect network connection issues because the RPi 3 is connected with an ethernet cable to an Asus ZenWifi AX mesh access point/router (and I've tried a different ethernet cable to be sure) and has a consistent average latency of around 5ms.

I've also tested the RPi 3 connected through WiFi (with USB N-compatible Wifi Adapter through a 2.4ghz connection) and I have not experienced any problems.

I'm aware of #1515 and https://github.com/raspberrypi/linux/issues/3292#issuecomment-774523727 regarding ethernet power saving, but that feature is not on the RPi 3. I reckon the issue is not in the Shairport Sync code, but in the ethernet port of the RPi. I hope my testing helps narrowing down the problem.

@Miladnorouzi77 are you using Wifi or Ethernet?

### Ethernet logs
```
Sync Error ms | Net Sync PPM | All Sync PPM | Missing | Resend Reqs | Output FPS (r) | Output FPS (c)
         2.48        -1640.0         1855.2       267             8         44015.62         44015.62
         3.45        -1954.4         2130.0       267             8         44015.57         44015.57
         3.15        -1730.6         2042.2       267             8         44015.59         44015.59
         3.50        -2050.7         2299.9       267             8         44015.74         44015.74
         9.53        -1880.7         1886.4       534             9              N/A              N/A
         6.43        -1283.1         1283.1       534             9         44017.61         44017.61
         5.04        -2407.6         2407.6       534             9         44016.10         44016.10
         3.34        -1928.9         2291.4       534             9         44016.21         44016.21
         2.52        -1637.1         1999.7       534             9         44015.18         44015.18
         3.10        -1801.4         1948.7       534             9         44016.23         44016.23
         3.18        -1923.2         2189.5       534             9         44015.23         44015.23
         3.29        -2022.3         2231.9       534             9         44015.86         44015.86
         3.40        -1928.9         2144.1       534            11         44015.76         44015.76
         3.38        -2090.3         2271.6       534            11         44015.77         44015.77
         3.21        -1937.4         2084.7       534            11         44015.66         44015.66
         3.36        -1948.7         2226.3       534            11         44015.52         44015.52
         3.01        -1841.1         2084.7       534            11         44015.65         44015.65
         2.92        -1758.9         2132.8       534            11         44015.72         44015.72
         2.74        -1685.3         1894.9       534            11         44015.80         44015.80
         3.40        -1982.7         2141.3       534            11         44015.77         44015.77
         6.41        -1807.1         1965.7       800            12              N/A              N/A
         4.90         -892.2          892.2       800            12         44015.36         44015.36
         4.63        -2370.7         2376.4       800            12         44015.00         44015.00
         3.23        -1979.9         2098.8       800            12         44015.12         44015.12
         3.18        -1954.4         2124.3       800            12         44015.12         44015.12
         3.32        -1906.2         2059.2       800            12         44015.39         44015.39
         2.64        -1600.3         2019.5       800            12         44015.44         44015.44
         2.86        -1736.3         1906.2       800            15         44015.64         44015.64
         3.19        -1951.5         2217.8       800            15         44015.41         44015.41
         3.48        -1920.4         2079.0       800            15         44015.85         44015.85
         3.50        -2047.8         2212.1       800            15         44015.41         44015.41
         3.49        -2011.0         2271.6       800            15         44015.44         44015.44
         3.21        -1940.2         2149.8       800            15         44015.79         44015.79
         3.27        -1928.9         2104.5       800            15         44015.67         44015.67
         3.19        -1971.4         2101.6       800            15         44015.68         44015.68
         2.90        -1877.9         2155.5       800            15         44015.52         44015.52
         9.10         -776.1          776.1      1067            16              N/A              N/A
         5.98        -2359.4         2359.4      1067            16         44017.10         44017.10
         3.83        -2067.7         2237.6      1067            16         44016.31         44016.31
```

### Wifi logs
```
Sync Error ms | Net Sync PPM | All Sync PPM | Missing | Resend Reqs | Output FPS (r) | Output FPS (c)
         9.18        -2588.8         2588.8         0             0         44015.85         44015.85
         4.52        -2299.9         2305.6         0             0         44014.46         44014.46
         3.18        -1960.0         2130.0         0             0         44015.93         44015.93
```

(small sample because there are no issues)

**Comment by mikebrady** [comment]
Thanks @ErikFontanel for the information! Apart from large numbers of missing packets of audio, the statistics reveal big problems with synchronisation. The level of interpolation being done -- around 2,000 parts per million -- is extremely high. It might be due to three possible things: a problem with AirFoil, a problem with DietPi or a problem with the output DAC. Anything you can do to explore these would be really illuminating.

1. It would be interesting to see statistics for audio coming directly from the Mac's native AirPlay facilities, such as by selecting the RPi3 from the Sound Output system preference. This would eliminate any possible problems with AirFoil.
2. A second investigation would be to log the behaviour of the same system but with Raspberry Pi OS in place of DietPi.
4. Finally, if you could output to a different DAC, it would be interesting to see if it made any difference.

**Comment by ErikFontanel** [comment]
I suspect it's the DAC, I'm using a Xone:23C which is unsupported on Linux (no drivers) but works for general playback over USB. It never has been a problem really, and over Wifi I don't experience issues with lag.

## RPi 3 > Direct Airplay stream
```
Sync Error ms | Net Sync PPM | All Sync PPM | Missing | Resend Reqs | Output FPS (r) | Output FPS (c)         5.72         -798.2          798.2         0             0              N/A              N/A
         4.39        -2444.4         2444.4         0             0         44013.73         44013.73
         3.34        -1926.0         1926.0         0             0         44013.63         44013.63
         3.40        -1903.4         1903.4         0             0         44014.68         44014.68
         3.34        -1937.4         1937.4         0             0         44014.94         44014.94
```

## Zero W + Hifiberry DAC
I tried logging the Zero W which has a Hifiberry DAC and is also running DietPi but oddly enough `shairport-sync --statistics` does not generate any output after connecting through Airfoil or direct Airplay.

When I have some more time I will connect the Hifiberry DAC to the RPi 3 and do some logging.

**Comment by mikebrady** [comment]
Thanks again. You might find the statistics in the system log. On (slightly) older versions of Shairport Sync you have to enter `-u` to get logs and statistics on the command line — they used to go to the system log by default. On the latest versions, the `-u` isn’t needed and logs and statistics come to STDERR by default.

**Comment by Miladnorouzi77** [comment]
Hey Erik, i was using wifi but after your problem i decide to connect rpi to the exact router with the Ethernet cable. now its REALLY SMOOTH, and my problem is totally GONE. @mikebrady  look like the problem was the wifi router . i dont know why but its really working well with ethernet cable.

**Comment by ErikFontanel** [comment]
Alright, thanks! -u did the trick

## Zero W > Direct Airplay stream

```
Sync Error ms | Net Sync PPM | All Sync PPM | Missing | Resend Reqs | Output FPS (r) | Output FPS (c)
        -0.18          0.0          0.0       0           0            N/A            N/A
        -0.54          8.5          8.5       0           0       44099.98       44099.98
        -0.61         11.3         11.3       0           0       44100.04       44100.04
        -0.55          2.8          2.8       0           0       44099.92       44099.92
        -0.65          8.5          8.5       0           0       44099.96       44099.95
        -0.61          0.0          0.0       0           1       44099.89       44099.89
        -0.54          5.7          5.7       0           1       44099.97       44099.97
        -0.48          8.5          8.5       0           1       44099.95       44099.95
```

It's definitely the DAC on the RPi 3, I guess there is some weirdness going on with the board when it's using ethernet too. Wifi works perfectly anyway, so I'll just use that for now.

**Comment by ErikFontanel** [comment]
As a sanity check I tested with the Hifiberry DAC Plus connected to the RPi 3 and it's clear that my Xone:23C usb DAC definitely has some issues with playback. Maybe something to do with the ethernet + USB bus that's causing some issue. But everything is running smoothly now so I don't think it's related to Shairport Sync

```
Sync Error ms | Net Sync PPM | All Sync PPM | Missing | Resend Reqs | Output FPS (r) | Output FPS (c)
         2.33           60.1          214.6         0             0              N/A              N/A
         1.32         -169.9          793.1         0             0         44099.67         44099.67
         1.16           53.8          614.6         0             0         44099.96         44099.96
         1.29         -116.1          733.6         0             0         44099.89         44099.89
         1.17          -48.2          676.9         0             0         44099.92         44099.92
         1.24          -39.7          617.5         0             0         44100.00         44100.00
         1.10           59.5          575.0         0             0         44099.98         44099.98
         1.27          -39.7          657.1         0             0         44100.01         44100.01
         0.68          226.6          770.4         0             0         44099.99         44099.99
```

**Comment by mikebrady** [comment]
Very interesting, thanks.
