### ISSUE TITLE
[Problem]: AirPlay 2 -> Unable to add accessory to Apple Home

### ISSUE THREAD

**Issue by PalmTamino** [mikebrady/shairport-sync#1612]
### What happened?

I tried to add my Airplay 2 device running this software to apple home by following this guide: https://github.com/mikebrady/shairport-sync/blob/master/ADDINGTOHOME.md

But i got an error in apple home after clicking on the device which appeared successfully. 
![signal-2023-01-03-141306](https://user-images.githubusercontent.com/36358673/210364481-638283c8-5e58-4d4a-8a56-9e0a471e5513.jpeg)

### Relevant log output

```shell
Where to get? Is it needed?
```

### Configuration Information.

>> Display Config Start.

From "uname -a":
 Linux raspberrypi 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux

From /etc/os-release:
 Debian GNU/Linux 11 (bullseye)

From /sys/firmware/devicetree/base/model:
 Raspberry Pi 3 Model B Rev 1.2

Shairport Sync Version String:
 4.1.1-2-g6240fd83-AirPlay2-OpenSSL-Avahi-ALSA-soxr-sysconfdir:/etc

Command Line:
 shairport-sync --displayConfig

Configuration File:
 /etc/shairport-sync.conf

Configuration File Settings:
 general :
 {
   name = "Tamino's Zimmer";
 };

>> Display Config End.
>> Goodbye!

### How did you install Shairport Sync?

A package manager (apt, apt install, yum, pkg, etc.)

### Check previous issues

- [X] Confirm

**Comment by mikebrady** [comment]
Thanks. It should be working — maybe there’s something in #1246 that might help?

**Comment by PalmTamino** [comment]
> Thanks. It should be working — maybe there’s something in #1246 that might help?

Restarting phone didn't help. Still have the issue unfortunately :/

**Comment by NilsMinten** [comment]
I have the same issue, when looking at the verbose logs I can see the following items pop up. 

```
97.074935171 "rtsp.c:2942" Connection 5: Remote Control connection from {{ ip-v6 }} ("Nils’ iPhone") to self at {{ ip-v6 }}.
         0.037944062 "rtsp.c:2133" pair-add cb for {{ device-id }}
         0.037572552 "rtsp.c:1372" Connection 5: Connection closed by client.
```

So far I've rebooted my device a few times along with the shairport server, the iPhone just seems to give up as soon as the `pair-add` happens.

**Comment by mikebrady** [comment]
Thanks. Some users have had success trying this: in the Home app > Home settings "Allow Speaker & TV access", select the option "Anyone On the Same Network".

**Comment by NilsMinten** [comment]
Enabling that fixed it instantly, thanks for the quick response!

**Comment by PalmTamino** [comment]
> Thanks. Some users have had success trying this: in the Home app > Home settings "Allow Speaker & TV access", select the option "Anyone On the Same Network".

Nice that it helped, for me I still get the same error 
![E466C9E2-5617-411B-9D76-B64854433F59](https://user-images.githubusercontent.com/36358673/226736828-b21939c9-9ade-4e4b-ab2f-d95a8499e593.jpeg)

**Comment by mikebrady** [comment]
That’s seems to be a different error to the original, so yours might be a different kind of issue.

**Comment by ajones45** [comment]
Hi 

I was having this issue too and even with the "allow anyone on the same network" I was continuing to have this issue. 

In case anyone else gets to this thread and is still stuck: 
I just had to remove the "require password" option below the "anyone on same network" option in the home app.

It immediately started working again. 


PS thanks so much for all the support on this project. I use it literally every day and its rock solid, and works perfectly now!

**Comment by mikebrady** [comment]
Thanks for the information and the kind words. I've added an extra phrase to the ADDINGTOHOME guide.
