### ISSUE TITLE
Periodic sound degradation and echo

### ISSUE THREAD

**Issue by exa062** [mikebrady/shairport-sync#251]
I am using shairport-sync_2.8.1-0ppa1~trusty_amd64.deb on Lubuntu 14.4 with an asynchronous USB DAC.  I experience periodic sound degradation, the sound becomes scratchy and duplicated like an echo effect.  After 30 seconds or so the sound normalizes.  The issue reappears periodically, every 15 min to 2.5 hours.  By trial and error, it appears the best settings that make the issue least frequent are:

drift = 0;  (the default value is 88)
resync_threshold = 0;

I get much better results with soxr correction compared to basic correction.

Is it possible to turn off the synchronization for single output applications? I don't have the issues with older Shairport implementations that don't have the synchronization capabilities. 

Many thanks!

**Comment by mikebrady** [comment]
It's not possible, I'm afraid. Could you run `shairport-sync -V` and let me know the result? It may be that you can send the output to a pipe and then route it through `aplay`. 

What kind of DAC is it, exactly?

Regards
Mike

**Comment by exa062** [comment]
Mike, thank you for the prompt reply. It is an exaSound DAC. Streaming takes place with exchange of blocks of data with speed higher than the playback rate, followed with periods of no data exchange.  Eventually the process stabilizes and the average rate is dictated by the DAC master clock.  

Best,
George

**Comment by mikebrady** [comment]
The overall issue here is that the rate at which audio is sent from, say, iTunes, is going to be different from the rate at which it will be read by the DAC. So, if synchronisation was off, there are bound to be buffer overruns or underruns.

Are you the George at exaSound, by any chance?

Mike

**Comment by mikebrady** [comment]
George, is there any way you can think of, in principle, how the true latency of a frame about to be sent to an exaSound device could be had, I wonder?

**Comment by exa062** [comment]
I am, good to meet you, Mike. The ALSA driver implements snd_pcm_delay - 
http://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga012e8b999070e72ab23514f25e7d6482

It represents the length of time it will take for the next piece of data passed to snd_pcm_writei soon to reach the analog side of the DAC. So it's a sum of the amount of data that's sitting in buffers but not played yet.

**Comment by mikebrady** [comment]
Good to meet you too. Let me have a think and a look at this!

**Comment by mikebrady** [comment]
Okay, so I've modified a version of Shairport Sync to use `snd_pcm_delay` rather than `snd_pcm_avail_delay`. It's in a new branch of the git archive, called `modify_delay_check`. Would you be kind enough to give it a try?

Mike

**Comment by exa062** [comment]
Thank you, Mike. That was quick!  I am working on it.

**Comment by exa062** [comment]
I have the custom version compiled up and running.  I had an immediate subjective impression that it sounded much better than before.  It worked flawlessly for approximately 64 minutes, then there was an "echo" event for about 15 sec.  Six minutes later there was a second, a bit worse echo event that lasted for about 25sec. 

Is there anything that I can do on my side to help with the troubleshooting? Thank you! George

**Comment by mikebrady** [comment]
Hi George. It would be great if you could turn on a few diagnostic settings in the configuration file: set `log_verbosity` to 1 and statistics to `yes` and let me see them for a run which includes the "echo". Would there be a chance that you might be able to record the odd sound part of it?

**Comment by exa062** [comment]
Mike, please check the attached file. I will try to record the echo.
[shairport-sync-drift.txt](https://github.com/mikebrady/shairport-sync/files/189490/shairport-sync-drift.txt)

**Comment by mikebrady** [comment]
Thanks.

Is it still the case that you have turned off resync and set the drift tolerance to 0?

And has the `audio_backend_buffer_desired_length` has been set to something different, I wonder? The standard setting is 6,615.

I wonder what the logs would look like if you left the drift, resync, (and `audio_backend_buffer_desired_length` ?) settings at default?

For testing purposes, I would be inclined to leave the interpolation at "basic", even though the disturbance is more audible.

In any case, it looks like the source and the DAC are not being kept in sync. Here are two logs from a WiFi connected Raspberry Pi driving a [modest!] Topping TP30. (There are some extraneous log entries as well.) You'll see that the drift is being kept in check, and that the buffer size stays pretty constant, whereas in your log, the trend is down. I wonder if the "echo" events and suchlike are being caused when, say, the buffer empties...

First, late last night from an iMac connected via Ethernet to the router:

```
Mar 25 00:18:23 raspberrypi shairport-sync[8634]: New RTSP connection on port 5000
Mar 25 00:18:24 raspberrypi shairport-sync[8634]: Play connection from user agent "iTunes/12.3.3 (Macintosh; OS X 10.11.4)".
Mar 25 00:18:24 raspberrypi shairport-sync[8634]: Active-Remote string seen: "1906813185".
Mar 25 00:18:24 raspberrypi shairport-sync[8634]: DACP-ID string seen: "82E83B61395E5BC7".
Mar 25 00:18:24 raspberrypi shairport-sync[8634]: Connection from IPv4: 192.168.2.12:64529
Mar 25 00:18:56 raspberrypi shairport-sync[8634]: Sync error: -2.0 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 4802, min and max buffer occupancy 260 and 269.
Mar 25 00:19:26 raspberrypi shairport-sync[8634]: Sync error: 1.2 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6080, min and max buffer occupancy 262 and 264.
Mar 25 00:19:56 raspberrypi shairport-sync[8634]: Sync error: -0.6 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6156, min and max buffer occupancy 260 and 264.
Mar 25 00:20:26 raspberrypi shairport-sync[8634]: Sync error: -0.9 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6167, min and max buffer occupancy 261 and 264.
Mar 25 00:20:44 raspberrypi wpa_supplicant[406]: wlan0: WPA: Group rekeying completed with f4:ec:38:e6:70:82 [GTK=CCMP]
Mar 25 00:20:56 raspberrypi shairport-sync[8634]: Sync error: 3.3 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6140, min and max buffer occupancy 260 and 264.
Mar 25 00:21:26 raspberrypi shairport-sync[8634]: Sync error: 1.0 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6212, min and max buffer occupancy 262 and 264.
Mar 25 00:21:56 raspberrypi shairport-sync[8634]: Sync error: 2.5 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6217, min and max buffer occupancy 262 and 264.
Mar 25 00:22:29 raspberrypi shairport-sync[8634]: Sync error: 21.5 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 4438, min and max buffer occupancy 260 and 270.
Mar 25 00:22:59 raspberrypi shairport-sync[8634]: Sync error: 18.5 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6139, min and max buffer occupancy 260 and 264.
Mar 25 00:23:29 raspberrypi shairport-sync[8634]: Sync error: 20.7 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6177, min and max buffer occupancy 260 and 264.
Mar 25 00:23:59 raspberrypi shairport-sync[8634]: Sync error: 22.4 (frames); net correction: 0.8 (ppm); corrections: 0.8 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 4023, min and max buffer occupancy 262 and 271.
Mar 25 00:24:29 raspberrypi shairport-sync[8634]: Sync error: 25.5 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6090, min and max buffer occupancy 261 and 264.
Mar 25 00:24:59 raspberrypi shairport-sync[8634]: Sync error: 22.6 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6236, min and max buffer occupancy 261 and 264.
Mar 25 00:25:29 raspberrypi shairport-sync[8634]: Sync error: 24.1 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6189, min and max buffer occupancy 260 and 264.
Mar 25 00:25:59 raspberrypi shairport-sync[8634]: Sync error: 26.2 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6220, min and max buffer occupancy 260 and 264.
Mar 25 00:26:29 raspberrypi shairport-sync[8634]: Sync error: 25.0 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 6239, min and max buffer occupancy 261 and 264.
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: RTSP shutdown requested.
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: Closing down RTSP conversation thread...
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: Shut down audio, control and timing threads
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: Audio receiver -- Server RTP thread interrupted. terminating.
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: Control RTP thread interrupted. terminating.
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: Timing thread interrupted. terminating.
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: rtp_timing_sender thread interrupted. terminating.
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: Closed and terminated timer requester thread.
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: Timing RTP thread terminated.
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: timing thread joined
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: audio thread joined
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: control thread joined
Mar 25 00:26:52 raspberrypi shairport-sync[8634]: Player thread exit
```

and second, the same device begin fed from TuneIn Radio on an iPhone 6:

```
Mar 25 12:31:14 raspberrypi shairport-sync[8634]: New RTSP connection on port 5000
Mar 25 12:31:14 raspberrypi shairport-sync[8634]: Play connection from user agent "AirPlay/280.32.2".
Mar 25 12:31:14 raspberrypi shairport-sync[8634]: Active-Remote string seen: "2641154604".
Mar 25 12:31:14 raspberrypi shairport-sync[8634]: DACP-ID string seen: "14678D65D8DC67D0".
Mar 25 12:31:14 raspberrypi shairport-sync[8634]: Connection from IPv6: 2001:770:1df:0:8ce:ae93:1cc5:9982:64334
Mar 25 12:31:14 raspberrypi shairport-sync[8634]: Closing down RTSP conversation thread...
Mar 25 12:31:46 raspberrypi shairport-sync[8634]: Sync error: -1760.8 (frames); net correction: 3.8 (ppm); corrections: 3.8 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 4171, min and max buffer occupancy 218 and 236.
Mar 25 12:32:16 raspberrypi shairport-sync[8634]: Sync error: -1659.2 (frames); net correction: 59.0 (ppm); corrections: 59.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 2670, min and max buffer occupancy 216 and 240.
Mar 25 12:32:29 raspberrypi sudo[8688]: pam_unix(sudo:session): session closed for user root
Mar 25 12:32:37 raspberrypi shairport-sync[8634]: Error -- ALSA device in incorrect state (4) for play.
Mar 25 12:32:46 raspberrypi shairport-sync[8634]: Sync error: -703.1 (frames); net correction: 574.5 (ppm); corrections: 739.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 0, min and max buffer occupancy 230 and 252.
Mar 25 12:33:16 raspberrypi shairport-sync[8634]: Sync error: 64.7 (frames); net correction: -105.1 (ppm); corrections: 106.6 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 3744, min and max buffer occupancy 230 and 243.
Mar 25 12:33:46 raspberrypi shairport-sync[8634]: Sync error: 65.8 (frames); net correction: -105.8 (ppm); corrections: 105.8 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5668, min and max buffer occupancy 228 and 237.
Mar 25 12:34:16 raspberrypi shairport-sync[8634]: Sync error: 65.2 (frames); net correction: -105.8 (ppm); corrections: 105.8 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5730, min and max buffer occupancy 221 and 237.
Mar 25 12:34:46 raspberrypi shairport-sync[8634]: Sync error: 66.6 (frames); net correction: -106.6 (ppm); corrections: 106.6 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5836, min and max buffer occupancy 230 and 253.
Mar 25 12:35:16 raspberrypi shairport-sync[8634]: Sync error: 66.2 (frames); net correction: -104.3 (ppm); corrections: 104.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5720, min and max buffer occupancy 239 and 253.
Mar 25 12:35:46 raspberrypi shairport-sync[8634]: Sync error: 66.1 (frames); net correction: -107.3 (ppm); corrections: 107.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5983, min and max buffer occupancy 239 and 252.
Mar 25 12:36:16 raspberrypi shairport-sync[8634]: Sync error: 66.3 (frames); net correction: -105.8 (ppm); corrections: 105.8 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5607, min and max buffer occupancy 239 and 253.
Mar 25 12:36:46 raspberrypi shairport-sync[8634]: Sync error: 65.6 (frames); net correction: -105.8 (ppm); corrections: 105.8 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5730, min and max buffer occupancy 238 and 252.
Mar 25 12:37:16 raspberrypi shairport-sync[8634]: Sync error: 64.8 (frames); net correction: -113.4 (ppm); corrections: 116.4 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5700, min and max buffer occupancy 228 and 252.
Mar 25 12:37:46 raspberrypi shairport-sync[8634]: Sync error: 65.8 (frames); net correction: -100.5 (ppm); corrections: 100.5 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5659, min and max buffer occupancy 239 and 253.
Mar 25 12:38:16 raspberrypi shairport-sync[8634]: Sync error: 63.9 (frames); net correction: -101.3 (ppm); corrections: 101.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5696, min and max buffer occupancy 230 and 253.
Mar 25 12:38:46 raspberrypi shairport-sync[8634]: Sync error: 64.8 (frames); net correction: -119.4 (ppm); corrections: 122.5 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 4326, min and max buffer occupancy 238 and 256.
Mar 25 12:39:16 raspberrypi shairport-sync[8634]: Sync error: 65.8 (frames); net correction: -98.3 (ppm); corrections: 102.8 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 4403, min and max buffer occupancy 221 and 253.
Mar 25 12:39:46 raspberrypi shairport-sync[8634]: Sync error: 66.6 (frames); net correction: -105.1 (ppm); corrections: 105.1 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5816, min and max buffer occupancy 238 and 253.
Mar 25 12:40:16 raspberrypi shairport-sync[8634]: Sync error: 65.7 (frames); net correction: -107.3 (ppm); corrections: 110.4 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5827, min and max buffer occupancy 239 and 252.
Mar 25 12:40:44 raspberrypi wpa_supplicant[406]: wlan0: WPA: Group rekeying completed with f4:ec:38:e6:70:82 [GTK=CCMP]
Mar 25 12:40:46 raspberrypi shairport-sync[8634]: Sync error: 65.4 (frames); net correction: -105.1 (ppm); corrections: 105.1 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5907, min and max buffer occupancy 236 and 253.
Mar 25 12:41:16 raspberrypi shairport-sync[8634]: Sync error: 59.4 (frames); net correction: -124.0 (ppm); corrections: 124.0 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 4153, min and max buffer occupancy 237 and 256.
Mar 25 12:41:46 raspberrypi shairport-sync[8634]: Sync error: 54.1 (frames); net correction: -126.2 (ppm); corrections: 129.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5734, min and max buffer occupancy 238 and 252.
Mar 25 12:42:16 raspberrypi shairport-sync[8634]: Sync error: 57.2 (frames); net correction: -69.5 (ppm); corrections: 69.5 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5698, min and max buffer occupancy 237 and 252.
Mar 25 12:42:46 raspberrypi shairport-sync[8634]: Sync error: 56.8 (frames); net correction: -104.3 (ppm); corrections: 104.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5864, min and max buffer occupancy 238 and 253.
Mar 25 12:43:16 raspberrypi shairport-sync[8634]: Sync error: 50.1 (frames); net correction: -111.1 (ppm); corrections: 111.1 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 4055, min and max buffer occupancy 239 and 254.
Mar 25 12:43:46 raspberrypi shairport-sync[8634]: Sync error: 66.2 (frames); net correction: -105.8 (ppm); corrections: 107.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5614, min and max buffer occupancy 238 and 252.
Mar 25 12:44:16 raspberrypi shairport-sync[8634]: Sync error: 62.0 (frames); net correction: -136.8 (ppm); corrections: 139.9 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5539, min and max buffer occupancy 238 and 252.
Mar 25 12:44:46 raspberrypi shairport-sync[8634]: Sync error: 53.1 (frames); net correction: -77.1 (ppm); corrections: 83.2 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5223, min and max buffer occupancy 238 and 252.
Mar 25 12:45:16 raspberrypi shairport-sync[8634]: Sync error: 66.3 (frames); net correction: -105.1 (ppm); corrections: 108.1 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5779, min and max buffer occupancy 236 and 252.
Mar 25 12:45:46 raspberrypi shairport-sync[8634]: Sync error: 54.4 (frames); net correction: -134.6 (ppm); corrections: 134.6 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5527, min and max buffer occupancy 238 and 253.
Mar 25 12:46:16 raspberrypi shairport-sync[8634]: Sync error: 61.3 (frames); net correction: -72.6 (ppm); corrections: 74.1 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5857, min and max buffer occupancy 238 and 253.
Mar 25 12:46:46 raspberrypi shairport-sync[8634]: Sync error: 65.6 (frames); net correction: -109.6 (ppm); corrections: 109.6 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5609, min and max buffer occupancy 238 and 253.
Mar 25 12:47:16 raspberrypi shairport-sync[8634]: Sync error: 65.8 (frames); net correction: -110.4 (ppm); corrections: 111.9 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5294, min and max buffer occupancy 238 and 253.
Mar 25 12:47:46 raspberrypi shairport-sync[8634]: Sync error: 56.1 (frames); net correction: -99.8 (ppm); corrections: 99.8 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5667, min and max buffer occupancy 237 and 253.
Mar 25 12:48:16 raspberrypi shairport-sync[8634]: Sync error: 60.1 (frames); net correction: -127.0 (ppm); corrections: 128.5 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5468, min and max buffer occupancy 238 and 253.
Mar 25 12:48:46 raspberrypi shairport-sync[8634]: Sync error: 57.9 (frames); net correction: -90.7 (ppm); corrections: 92.2 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5548, min and max buffer occupancy 238 and 252.
Mar 25 12:49:16 raspberrypi shairport-sync[8634]: Sync error: 64.5 (frames); net correction: -116.4 (ppm); corrections: 119.4 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5113, min and max buffer occupancy 237 and 253.
Mar 25 12:49:46 raspberrypi shairport-sync[8634]: Sync error: 60.1 (frames); net correction: -107.3 (ppm); corrections: 107.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5953, min and max buffer occupancy 236 and 252.
Mar 25 12:50:16 raspberrypi shairport-sync[8634]: Sync error: 65.5 (frames); net correction: -101.3 (ppm); corrections: 101.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5896, min and max buffer occupancy 238 and 253.
Mar 25 12:50:44 raspberrypi wpa_supplicant[406]: wlan0: WPA: Group rekeying completed with f4:ec:38:e6:70:82 [GTK=CCMP]
Mar 25 12:50:46 raspberrypi shairport-sync[8634]: Sync error: 63.5 (frames); net correction: -99.0 (ppm); corrections: 102.1 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5692, min and max buffer occupancy 219 and 252.
Mar 25 12:51:16 raspberrypi shairport-sync[8634]: Sync error: 62.8 (frames); net correction: -170.8 (ppm); corrections: 172.4 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5512, min and max buffer occupancy 231 and 253.
Mar 25 12:51:46 raspberrypi shairport-sync[8634]: Sync error: 43.6 (frames); net correction: -107.3 (ppm); corrections: 107.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5859, min and max buffer occupancy 238 and 252.
Mar 25 12:52:16 raspberrypi shairport-sync[8634]: Sync error: 34.5 (frames); net correction: -75.6 (ppm); corrections: 77.1 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5654, min and max buffer occupancy 239 and 253.
Mar 25 12:52:46 raspberrypi shairport-sync[8634]: Sync error: 57.3 (frames); net correction: -74.8 (ppm); corrections: 74.8 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 4906, min and max buffer occupancy 238 and 253.
Mar 25 12:53:16 raspberrypi shairport-sync[8634]: Sync error: 64.3 (frames); net correction: -108.1 (ppm); corrections: 111.1 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5700, min and max buffer occupancy 227 and 252.
Mar 25 12:53:46 raspberrypi shairport-sync[8634]: Sync error: 67.8 (frames); net correction: -104.3 (ppm); corrections: 104.3 (ppm); missing packets 0; late packets 0; too late packets 0; resend requests 0; min DAC queue size 5788, min and max buffer occupancy 217 and 237.
Mar 25 12:54:16 raspberrypi shairport-sync[8634]: Sync error: 67.3 (frames); net correction: -107.3 (ppm); corrections: 107.3 (ppm); missing packets 0; late packets 2; too late packets 0; resend requests 2; min DAC queue size 5716, min and max buffer occupancy 217 and 237.
Mar 25 12:54:46 raspberrypi shairport-sync[8634]: Sync error: 59.6 (frames); net correction: -134.6 (ppm); corrections: 134.6 (ppm); missing packets 0; late packets 4; too late packets 0; resend requests 4; min DAC queue size 5509, min and max buffer occupancy 216 and 237.
Mar 25 12:55:16 raspberrypi shairport-sync[8634]: Sync error: 55.0 (frames); net correction: -75.6 (ppm); corrections: 75.6 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5890, min and max buffer occupancy 215 and 252.
Mar 25 12:55:46 raspberrypi shairport-sync[8634]: Sync error: 58.4 (frames); net correction: -118.7 (ppm); corrections: 120.2 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5303, min and max buffer occupancy 217 and 253.
Mar 25 12:56:16 raspberrypi shairport-sync[8634]: Sync error: 66.0 (frames); net correction: -93.7 (ppm); corrections: 95.3 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5487, min and max buffer occupancy 217 and 253.
Mar 25 12:56:46 raspberrypi shairport-sync[8634]: Sync error: 66.2 (frames); net correction: -110.4 (ppm); corrections: 110.4 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5748, min and max buffer occupancy 238 and 253.
Mar 25 12:57:16 raspberrypi shairport-sync[8634]: Sync error: 66.8 (frames); net correction: -110.4 (ppm); corrections: 110.4 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5942, min and max buffer occupancy 239 and 253.
Mar 25 12:57:46 raspberrypi shairport-sync[8634]: Sync error: 65.4 (frames); net correction: -102.1 (ppm); corrections: 105.1 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5536, min and max buffer occupancy 239 and 253.
Mar 25 12:58:16 raspberrypi shairport-sync[8634]: Sync error: 66.3 (frames); net correction: -106.6 (ppm); corrections: 108.1 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5761, min and max buffer occupancy 238 and 253.
Mar 25 12:58:46 raspberrypi shairport-sync[8634]: Sync error: 66.5 (frames); net correction: -118.7 (ppm); corrections: 118.7 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5660, min and max buffer occupancy 237 and 253.
Mar 25 12:59:16 raspberrypi shairport-sync[8634]: Sync error: 65.6 (frames); net correction: -97.5 (ppm); corrections: 97.5 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5848, min and max buffer occupancy 239 and 252.
Mar 25 12:59:46 raspberrypi shairport-sync[8634]: Sync error: 63.5 (frames); net correction: -99.8 (ppm); corrections: 99.8 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5931, min and max buffer occupancy 239 and 253.
Mar 25 13:00:16 raspberrypi shairport-sync[8634]: Sync error: 66.6 (frames); net correction: -130.0 (ppm); corrections: 130.0 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 4386, min and max buffer occupancy 239 and 253.
Mar 25 13:00:44 raspberrypi wpa_supplicant[406]: wlan0: WPA: Group rekeying completed with f4:ec:38:e6:70:82 [GTK=CCMP]
Mar 25 13:00:46 raspberrypi shairport-sync[8634]: Sync error: 58.2 (frames); net correction: -93.7 (ppm); corrections: 93.7 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5898, min and max buffer occupancy 239 and 253.
Mar 25 13:01:16 raspberrypi shairport-sync[8634]: Sync error: 66.4 (frames); net correction: -104.3 (ppm); corrections: 105.8 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5712, min and max buffer occupancy 233 and 253.
Mar 25 13:01:46 raspberrypi shairport-sync[8634]: Sync error: 64.8 (frames); net correction: -136.1 (ppm); corrections: 136.1 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5323, min and max buffer occupancy 238 and 253.
Mar 25 13:02:16 raspberrypi shairport-sync[8634]: Sync error: 62.5 (frames); net correction: -79.4 (ppm); corrections: 80.9 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5451, min and max buffer occupancy 239 and 253.
Mar 25 13:02:46 raspberrypi shairport-sync[8634]: Sync error: 65.2 (frames); net correction: -109.6 (ppm); corrections: 109.6 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5721, min and max buffer occupancy 238 and 253.
Mar 25 13:03:16 raspberrypi shairport-sync[8634]: Sync error: 62.9 (frames); net correction: -107.3 (ppm); corrections: 107.3 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5338, min and max buffer occupancy 239 and 253.
Mar 25 13:03:46 raspberrypi shairport-sync[8634]: Sync error: 63.8 (frames); net correction: -108.9 (ppm); corrections: 110.4 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5640, min and max buffer occupancy 238 and 253.
Mar 25 13:04:16 raspberrypi shairport-sync[8634]: Sync error: 64.7 (frames); net correction: -119.4 (ppm); corrections: 121.0 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5452, min and max buffer occupancy 239 and 252.
Mar 25 13:04:46 raspberrypi shairport-sync[8634]: Sync error: 65.1 (frames); net correction: -100.5 (ppm); corrections: 100.5 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5930, min and max buffer occupancy 238 and 253.
Mar 25 13:05:13 raspberrypi sudo[5714]: pi : TTY=pts/0 ; PWD=/home/pi/shairport-sync ; USER=root ; COMMAND=/bin/journalctl -n 1000 -f
Mar 25 13:05:13 raspberrypi sudo[5714]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Mar 25 13:05:16 raspberrypi shairport-sync[8634]: Sync error: 66.1 (frames); net correction: -101.3 (ppm); corrections: 102.8 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 4635, min and max buffer occupancy 236 and 253.
Mar 25 13:05:46 raspberrypi shairport-sync[8634]: Sync error: 64.8 (frames); net correction: -106.6 (ppm); corrections: 108.1 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 4596, min and max buffer occupancy 238 and 253.
Mar 25 13:06:16 raspberrypi shairport-sync[8634]: Sync error: 65.1 (frames); net correction: -108.9 (ppm); corrections: 108.9 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5753, min and max buffer occupancy 237 and 253.
Mar 25 13:06:46 raspberrypi shairport-sync[8634]: Sync error: 64.8 (frames); net correction: -108.1 (ppm); corrections: 108.1 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5714, min and max buffer occupancy 239 and 252.
Mar 25 13:07:16 raspberrypi shairport-sync[8634]: Sync error: 66.0 (frames); net correction: -108.9 (ppm); corrections: 110.4 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5888, min and max buffer occupancy 239 and 253.
Mar 25 13:07:46 raspberrypi shairport-sync[8634]: Sync error: 65.5 (frames); net correction: -107.3 (ppm); corrections: 107.3 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5726, min and max buffer occupancy 239 and 253.
Mar 25 13:08:16 raspberrypi shairport-sync[8634]: Sync error: 66.6 (frames); net correction: -113.4 (ppm); corrections: 114.9 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5027, min and max buffer occupancy 216 and 252.
Mar 25 13:08:46 raspberrypi shairport-sync[8634]: Sync error: 67.1 (frames); net correction: -101.3 (ppm); corrections: 101.3 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5799, min and max buffer occupancy 226 and 237.
Mar 25 13:09:16 raspberrypi shairport-sync[8634]: Sync error: 66.6 (frames); net correction: -105.8 (ppm); corrections: 105.8 (ppm); missing packets 0; late packets 6; too late packets 0; resend requests 6; min DAC queue size 5740, min and max buffer occupancy 220 and 237.
```
It might take a little while to get to the bottom of this, and a few wrong turning might be made (!), but I'd be really interested to pursue it if you are.

**Comment by mikebrady** [comment]
[Update] Actually, I'm wrong about the trend of the buffer length being downwards – it stabilises due to the corrections of about 55 ppm evidenced at the end of your log.

**Comment by mikebrady** [comment]
[Update 2] I see the drift setting now, thanks. The initial sync error of 3,486.7 frames is very high – getting on for a tenth of a second. Can I just enquire if your Lubuntu is running in a virtual machine, or is it running natively on the NUC?

**Comment by exa062** [comment]
Mike, 

The original file contains several tests and I haven't organized it well, I am sorry.  All tests were taken with:
audio_backend_buffer_desired_length = 16384;
resync_threshold = 0;

Here is a new file with a single test. The conditions are:
audio_backend_buffer_desired_length = 16384;
drift = 4410
resync_threshold = 0;
 
Initially the sync error is huge -3400.  This is caused by filling up the buffers with streaming rate higher than the playback rate. After a while it stabilizes around  the value of  450 with corrections 40 - 50 ppm and min DAC queue size around 11500.  

Then we observe a sudden change:
Sync error: 3264004884.4, 4294612862.5
Corrections: 2840.9
Min DAC queue size: 1000000  (strange?)

At s point music playback continues normally.  The echo event occurs much later and I don't have the trace.  I am trying to catch it. 

I am not using virtual machines, both test computers, the i3 and the Celeron are handling the workload well. 
[Test-2.txt](https://github.com/mikebrady/shairport-sync/files/189603/Test-2.txt)

**Comment by mikebrady** [comment]
Thanks for this. Those numbers look to me like a 32-bit overflow happening somewhere in Shairport Sync – 4294967295 is 2^32-1. Let me see if I can chase that down. It may just be cosmetic – i.e. it may only affect the statistics display – but it needs to be sorted out.

**Comment by mikebrady** [comment]
George, is it possible that the drift is 441 rather than 4410. This is what I get with a drift of 4410 and resync disabled:

```
Mar 25 14:49:13 raspberrypi2 shairport-sync[869]: New RTSP connection on port 5000
Mar 25 14:49:14 raspberrypi2 shairport-sync[869]: Play connection from user agent "iTunes/12.3.3 (Macintosh; OS X 10.11.4)".
Mar 25 14:49:14 raspberrypi2 shairport-sync[869]: Active-Remote string seen: "2607499274".
Mar 25 14:49:14 raspberrypi2 shairport-sync[869]: DACP-ID string seen: "F18FE780B35CFD8D".
Mar 25 14:49:14 raspberrypi2 shairport-sync[869]: Connection from IPv4: 192.168.2.12:49411
Mar 25 14:49:39 raspberrypi2 sudo[1290]: pi : TTY=pts/0 ; PWD=/home/pi ; USER=root ; COMMAND=/bin/journalctl -n 100 -f
Mar 25 14:49:39 raspberrypi2 sudo[1290]: pam_unix(sudo:session): session opened for user root by pi(uid=0)
Mar 25 14:49:46 raspberrypi2 shairport-sync[869]: Sync error: -60.0 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 20; too late packets 0; resend requests 20; min DAC queue size 4413, min and max buffer occupancy 216 and 270.
Mar 25 14:50:04 raspberrypi2 wpa_supplicant[445]: wlan0: WPA: Group rekeying completed with 94:10:3e:93:5a:1a [GTK=CCMP]
Mar 25 14:50:16 raspberrypi2 shairport-sync[869]: Sync error: -183.0 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 71; too late packets 0; resend requests 71; min DAC queue size 15669, min and max buffer occupancy 210 and 237.
Mar 25 14:50:46 raspberrypi2 shairport-sync[869]: Sync error: -314.2 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 75; too late packets 0; resend requests 75; min DAC queue size 15549, min and max buffer occupancy 222 and 237.
Mar 25 14:51:16 raspberrypi2 shairport-sync[869]: Sync error: -439.2 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 76; too late packets 0; resend requests 76; min DAC queue size 15413, min and max buffer occupancy 230 and 237.
Mar 25 14:51:46 raspberrypi2 shairport-sync[869]: Sync error: -565.2 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 76; too late packets 0; resend requests 76; min DAC queue size 15309, min and max buffer occupancy 229 and 237.
Mar 25 14:52:16 raspberrypi2 shairport-sync[869]: Sync error: -689.6 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 76; too late packets 0; resend requests 76; min DAC queue size 15173, min and max buffer occupancy 226 and 237.
Mar 25 14:52:46 raspberrypi2 shairport-sync[869]: Sync error: -817.2 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 110; too late packets 0; resend requests 110; min DAC queue size 15029, min and max buffer occupancy 212 and 237.
Mar 25 14:53:16 raspberrypi2 shairport-sync[869]: Sync error: -943.7 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 125; too late packets 0; resend requests 125; min DAC queue size 14909, min and max buffer occupancy 162 and 237.
Mar 25 14:53:46 raspberrypi2 shairport-sync[869]: Sync error: -1068.4 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 125; too late packets 0; resend requests 125; min DAC queue size 14797, min and max buffer occupancy 231 and 237.
```
You'll see the drift isn't being corrected for at around 440 as it is with your Test-2.txt file.

Here it is with a drift limit of 410:

```
Mar 25 14:56:27 raspberrypi2 shairport-sync[4075]: New RTSP connection on port 5000
Mar 25 14:56:28 raspberrypi2 shairport-sync[4075]: Play connection from user agent "iTunes/12.3.3 (Macintosh; OS X 10.11.4)".
Mar 25 14:56:28 raspberrypi2 shairport-sync[4075]: Active-Remote string seen: "2607499274".
Mar 25 14:56:28 raspberrypi2 shairport-sync[4075]: DACP-ID string seen: "F18FE780B35CFD8D".
Mar 25 14:56:28 raspberrypi2 shairport-sync[4075]: Connection from IPv4: 192.168.2.12:49631
Mar 25 14:57:00 raspberrypi2 shairport-sync[4075]: Sync error: -57.0 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 13; too late packets 0; resend requests 13; min DAC queue size 4421, min and max buffer occupancy 169 and 270.
Mar 25 14:57:30 raspberrypi2 shairport-sync[4075]: Sync error: -180.7 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 80; too late packets 0; resend requests 80; min DAC queue size 15525, min and max buffer occupancy 171 and 237.
Mar 25 14:58:00 raspberrypi2 shairport-sync[4075]: Sync error: -307.0 (frames); net correction: 0.0 (ppm); corrections: 0.0 (ppm); missing packets 0; late packets 80; too late packets 0; resend requests 80; min DAC queue size 15541, min and max buffer occupancy 230 and 237.
Mar 25 14:58:30 raspberrypi2 shairport-sync[4075]: Sync error: -419.4 (frames); net correction: 47.6 (ppm); corrections: 47.6 (ppm); missing packets 0; late packets 133; too late packets 0; resend requests 134; min DAC queue size 14742, min and max buffer occupancy 186 and 239.
Mar 25 14:59:00 raspberrypi2 shairport-sync[4075]: Sync error: -434.6 (frames); net correction: 90.0 (ppm); corrections: 90.0 (ppm); missing packets 0; late packets 196; too late packets 0; resend requests 198; min DAC queue size 14108, min and max buffer occupancy 149 and 241.
Mar 25 14:59:30 raspberrypi2 shairport-sync[4075]: Sync error: -437.1 (frames); net correction: 97.5 (ppm); corrections: 97.5 (ppm); missing packets 0; late packets 260; too late packets 0; resend requests 260; min DAC queue size 14224, min and max buffer occupancy 198 and 241.
Mar 25 15:00:00 raspberrypi2 shairport-sync[4075]: Sync error: -437.2 (frames); net correction: 94.5 (ppm); corrections: 94.5 (ppm); missing packets 0; late packets 326; too late packets 0; resend requests 326; min DAC queue size 14757, min and max buffer occupancy 171 and 239.
Mar 25 15:00:04 raspberrypi2 wpa_supplicant[445]: wlan0: WPA: Group rekeying completed with 94:10:3e:93:5a:1a [GTK=CCMP]
Mar 25 15:00:30 raspberrypi2 shairport-sync[4075]: Sync error: -436.9 (frames); net correction: 94.5 (ppm); corrections: 94.5 (ppm); missing packets 0; late packets 365; too late packets 0; resend requests 365; min DAC queue size 14015, min and max buffer occupancy 234 and 241.
Mar 25 15:01:00 raspberrypi2 shairport-sync[4075]: Sync error: -437.2 (frames); net correction: 100.5 (ppm); corrections: 100.5 (ppm); missing packets 0; late packets 365; too late packets 0; resend requests 365; min DAC queue size 14558, min and max buffer occupancy 235 and 240.
Mar 25 15:01:30 raspberrypi2 shairport-sync[4075]: Sync error: -437.1 (frames); net correction: 90.7 (ppm); corrections: 90.7 (ppm); missing packets 0; late packets 365; too late packets 0; resend requests 365; min DAC queue size 14983, min and max buffer occupancy 229 and 238.
Mar 25 15:02:00 raspberrypi2 shairport-sync[4075]: Sync error: -437.3 (frames); net correction: 99.0 (ppm); corrections: 99.0 (ppm); missing packets 0; late packets 366; too late packets 0; resend requests 366; min DAC queue size 14898, min and max buffer occupancy 225 and 239.
Mar 25 15:02:30 raspberrypi2 shairport-sync[4075]: Sync error: -437.2 (frames); net correction: 90.0 (ppm); corrections: 90.0 (ppm); missing packets 0; late packets 404; too late packets 0; resend requests 405; min DAC queue size 14546, min and max buffer occupancy 186 and 240.
Mar 25 15:03:00 raspberrypi2 shairport-sync[4075]: Sync error: -437.2 (frames); net correction: 102.8 (ppm); corrections: 102.8 (ppm); missing packets 0; late packets 407; too late packets 0; resend requests 407; min DAC queue size 13659, min and max buffer occupancy 207 and 242.
Mar 25 15:03:30 raspberrypi2 shairport-sync[4075]: Sync error: -436.6 (frames); net correction: 87.7 (ppm); corrections: 87.7 (ppm); missing packets 0; late packets 409; too late packets 0; resend requests 409; min DAC queue size 14052, min and max buffer occupancy 178 and 241.
```

**Comment by mikebrady** [comment]
Hi George. I've done some bug hunting and added an option you sort-of suggested, and I'd be grateful if you'd try it out.

The update – 2.9.5.2 – has a number of changes to how DAC delay information is handled and what happens if it isn't available on occasion. It corrects at least one error misinterpreting a return error code of -1 as 4,294,967,295. (I wonder if it's possible that your driver occasionally is unable to return a delay value?)

The update also tidies up and possibly corrects some arithmetic sign overflow type and type-promotion errors due to incomplete observance of the rules of type conversion and promotion in C. These may result in more accurate estimates of when a sound session should begin, to start in sync.

A new `alsa` backend option to disable synchronisation is added: `disable_synchronization = "yes"` with a default of `"no"`. (See the installed `/etc/shairport-sync.conf.sample` file. to see where it should go.) This should be used with caution; sooner or later, the DAC will either overflow or underflow, giving audible discontinuities. They may happen only after a number of hours, however.

Some debug messages are tided up, some demoted to level 2 or 3, and some promoted to level 1.

**Comment by exa062** [comment]
Hi Mike,

Thank you for the time and energy you are pitting into this project.  We are very interested to get to the bottom of this and it is great to work with you.  I took some time off this weekend while you created the new version, now it is my turn.  

Back to your questions, the drift we used for the tests last week is 4410.  It appears the corrections kick in around the 300-320 mark.  

I still don't have for you a sound recording of the echo.  We are focusing on your new release and we found out that our snd_pcm_delay sometimes returns to you a negative value.  So we are sunk deep into our code looking for issues with buffer pointers. 

disable_synchronization = "yes" is not tested yet, we will do as soon as the negative return bug is fixed.

Thanks! George

**Comment by mikebrady** [comment]
Thanks for this. I'm not an alsa expert at all, but it occurs to me that, while  a negative delay value sounds a bit odd, a negative status from snd_pcm_write is not wrong. Shairport Sync didn't handle it properly -- I it rarely or never happened, it seems.. I believe there is at least one other bug in the way resends are dealt with, but that's a separate thing.

**Comment by mikebrady** [comment]
BTW, it still isn't dealing with `int32_t` to `int64_t` signed conversions as I expect it to, so there are still a few little problems.

**Comment by exa062** [comment]
Thank you for the update.  On our side we are exploring the parameters that control the data exchange between the ALSA driver and shairport-sync.  It appears that regardless of the value of audio_backend_buffer_desired_length, the PERIOD_SIZE used by the ALSA driver is always the same and it is too big.  Here is a dump of the driver settings when playback starts:

ACCESS:  RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 32
CHANNELS: 2
RATE: 44100
PERIOD_TIME: (371519 371520)
PERIOD_SIZE: 16384
PERIOD_BYTES: 65536
PERIODS: 4
BUFFER_TIME: (1486077 1486078)
BUFFER_SIZE: 65536
BUFFER_BYTES: 262144
TICK_TIME: [0 0]

Another observation is that sometimes snd_pcm_avail() returns data size bigger than the entire ALSA buffer.  This is the cause for the calculated negative delays by snd_pcm_delay ().

At this time we are trying to modify your code to set PERIOD_SIZE .  The following quick and dirty code goes to audio_alsa.c, row 361:  

snd_pcm_uframes_t frames = config.audio_backend_buffer_desired_length / 4;     // TODO: use periods count instead hardcoded to 4
 ret = snd_pcm_hw_params_set_period_size_near(alsa_handle, alsa_params, &frames, &dir);

This modification sets the system in much better state. See the attached file. 
•	drift tolerance is 441 frames.  	//it is now for real 441, not 4410
•	audio backend desired buffer length is 8192.
•	Note PERIOD_SIZE: 2048 - in our experience with other players this is the optimal size for our driver. 

Everything goes smooth until the 11th minute, when we get "Delay error when checking running latency".  The timing varies, it can be 2 minutes or 20 minutes.

A quick note - this is how our driver works: 
•	We always have PERIODS: 4
•	We use snd_pcm_avail_update() to check how much data is available in the ALSA buffer and when there is data for one complete period we read it as one block.  This is provided that the DAC has space in the hardware buffer to store the new data. 

Your code is quite complicated, can you give us a hint how you check if there is available space in the ALSA buffer before sending data? This may be the key why we get more data than the buffer size. 

[test-4.txt](https://github.com/mikebrady/shairport-sync/files/193601/test-4.txt)

**Comment by mikebrady** [comment]
Thanks very much for the post. 

Overall, I've tried to stay as far away from the internal settings and details of `alsa` as possible. I'm kinda relying on the idea that the drivers know what's best for them. It would be a bit problematic to have Shairport Sync have a bunch of different settings for different DACs. Of course, for testing and debugging, that's fine and appropriate, but for long term use, I guess the approach should be that the driver knows best. (I'm not sure how realistic that is, BTW, but it makes a bit of sense to me.)

When Shairport Sync is initialising the `alsa` output device it asks for: interleaved stereo, 16 bit signed PCM, 44100Hz operation. If the buffer size is too small to accommodate the backend buffer of the desired length, it will try to expand it. Everything else it leaves alone. From your post, I am thinking that setting the buffer size is an unnecessary complication, so I've removed the code, leaving all settings at their default values except, as detailed above, for asking for CD-quality and format transfers. Thus, the driver will have its default values for everything else.

In regard to the relationship between `audio_backend_buffer_desired_length` and the `alsa` buffer size, it was really intended to check that the `alsa` buffer would be large enough to accommodate the desired size with a bit of headroom. What will happen now is simply a check that the buffer is large enough, without changing it. Shairport Sync will print a message and die if there is insufficient room.

Shairport Sync does not actually check for available space before sending data – it uses a blocking version of `snd_pcm_writei` to try to keep things simple. Each write is of not more than about 441 audio frames, typically 353  audio frames.

The way Shairport Sync works with timings is really pretty independent of the DAC, apart from getting its latency:
* When a play is about to begin, it tries to work out exactly when to start sending frames of audio to the DAC so the programme starts to play at precisely the correct time. It will send silent frames for a while and measure the latency to get a fix on when to start sending the programme material. It uses the time, the time stamps present in the data and the `audio_backend_latency_offset` to do this.
* Once the stream has been started at the right time, it then uses the `audio_backend_buffer_desired_length` figure along with the time and the timestamp data again to work out how much extra data to send out to the output device to add audio frames fast enough to create a standing latency in the device's output buffer of `audio_backend_buffer_desired_length`. So, for example, if you wanted 0.15 seconds of audio to be in the buffer at all times, you would release all audio into it that was due to be played in the next 0.15 seconds and keep doing that forever.
* If all the timings are correct, that standing latency should stay constant. If the DAC is running fast relative to the source, the length of this buffer of samples will tend to drop. If the DAC is running slow, then samples will accumulate faster than they are consumed by the DAC. Shairport Sync will interpolate to keep the buffer length constant.

I've just pushed another update with changes to the `delay()` function. It turns out that a negative result from `get_pcm_delay()` is legitimate, so I can't use a negative value as an error code. So, I've changed the function `delay()` to return a delay and a status separately. It logs a message when the status returns a negative (i.e. an error) value. If it reports a negative delay count, it logs it and pretends it's zero. Not sure if it should simply ignore it altogether – let me know.

I've tried to tighten up on arithmetic and sign errors too, and have resolved the resend error bug – it was occurring then all the incoming frames were gone.

**Comment by mikebrady** [comment]
What I should have said also was that, now, if `pcm_get_delay()` occasionally returns a negative status (not a negative latency), Shairport Sync will simply ignore it and not check synchronisation on that occasion. So, even though it logs it at present, it is not necessarily a problem if it happens occasionally. I simulated it happening around one time in 10,000 and it seemed to be okay.

**Comment by mikebrady** [comment]
I should run a diagnostics to see how standard DACs compare to the figures you give above for buffer size etc. I note in the log that the minimum DAC size reported was well down on the 8,192 requested, so it may be that – I'm really guessing here – the buffers are relatively small compared to buffers on other DACs.

**Comment by mikebrady** [comment]
I've just pushed a small change which makes the check of buffer size advisory only – even if the buffer is too small, Shairport Sync will still go ahead – it won't die.

**Comment by mikebrady** [comment]
I might get a chance today to add a few settings to enable you to change the period size and stuff. Depends on how busy I am...

**Comment by mikebrady** [comment]
So, I pushed an update that allows you to set the period size and the buffer size. As I'm sure you know, they interact with one another. Anyway, at debug level 1 it now gives some information about alsa settings – here is an example:

```
Mar 30 12:43:24 raspberrypi shairport-sync[22053]: PCM handle name = 'hw:1'
Mar 30 12:43:24 raspberrypi shairport-sync[22053]: access type = RW_INTERLEAVED
Mar 30 12:43:24 raspberrypi shairport-sync[22053]: format = 'S16_LE' (Signed 16 bit Little Endian)
Mar 30 12:43:24 raspberrypi shairport-sync[22053]: subformat = 'STD' (Standard)
Mar 30 12:43:24 raspberrypi shairport-sync[22053]: channels = 2
Mar 30 12:43:24 raspberrypi shairport-sync[22053]: rate = 44100 bps
Mar 30 12:43:24 raspberrypi shairport-sync[22053]: period time = 23219 us
Mar 30 12:43:24 raspberrypi shairport-sync[22053]: period size = 1024 frames
Mar 30 12:43:25 raspberrypi shairport-sync[22053]: buffer time = 2972154 us
Mar 30 12:43:25 raspberrypi shairport-sync[22053]: buffer size = 131072 frames
Mar 30 12:43:25 raspberrypi shairport-sync[22053]: periods per buffer = 128 frames
Mar 30 12:43:25 raspberrypi shairport-sync[22053]: exact rate = 44100/1 bps
Mar 30 12:43:25 raspberrypi shairport-sync[22053]: significant bits = 16
```

I will not be able to give attention to this for another few days, I'm afraid.

**Comment by exa062** [comment]
Mike, with the changes you've made we are getting better results - thank you! The ball is in our court, there is something that we don't understand.  We still don't know what is the root cause of the problem.  I will take some time off and just think about it.  Then I will do more debugging and experimenting. I will get back to you as soon as I have any meaningful new information.

**Comment by mikebrady** [comment]
Perfect, thanks.

**Comment by mikebrady** [comment]
George, I've merged the changes in the `modify_delay_check` branch into the `development` branch, so the next time you are updating Shairport Sync, it would be worth changing back to the `development` branch.

**Comment by exa062** [comment]
Thank you, Mike. We will use the development branch.  No progress to report on our side.

**Comment by mikebrady** [comment]
Hi George, just FYI, those changes are now in the main `master` branch release, 2.8.4, along with some bug fixes. I'll close this issue pending any updates from you. All the best, Mike.

**Comment by exa062** [comment]
Thank you, Mike.  We haven’t given up on this project.  We will get back to it during the summer slowdown. 

Cheers, George.
