### ISSUE TITLE
Out of sync when using Tuneblade or Airfoil [Fixed]

### ISSUE THREAD

**Issue by tommcm1200** [mikebrady/shairport-sync#675]
Hi All,

Recently I've noticed both Tuneblade and Airfoil not playing audio in sync.  It's ok when streaming from using iTunes.  Receiving devices are Airport express, Bose SoundLink, and an RPi.  The RPi with Shairport Sync is the only device out of sync.  

Any assistance or advice to further troubleshoot would be much appreciated.

I'm streaming from a Win10 PC.

Versions:
Shairport v3.1.7
ITunes  v12.7.3.46
Airfoil v5.5.0 b4
Tunblade: v1.6.3

Thx.

**Comment by mikebrady** [comment]
Thanks for the post. I think this problem has been fixed already in the `development` build -- would you be kind enough to try it out please? (You can follow the procedure for updating as described on the [UPDATING.md](https://github.com/mikebrady/shairport-sync/blob/master/UPDATING.md) page -- it notes how to switch to the `development` branch.)

**Comment by tommcm** [comment]
thanks Mike.  I can confirm using the upgrading to the development branch has fixed sync problems.  

Interestingly the out of sync issues still remains for Tuneblade when TuneBlade is set to Buffer streaming mode (3 secs).  It's ok when set to Normal mode (2 secs).  Why would this be the case?

**Comment by mikebrady** [comment]
Thanks for the interesting extra piece of information. You are quite right -- it's because TuneBlade doesn't ever set the "Extension" bit in a sync packet like "official" sources do. (Sync packets are sent every second and contain latency information.) It'll take a few days to work around this.

**Comment by mikebrady** [comment]
Well, maybe not a few days -- I've just pushed a `development` update which should fix the problem. It sure would be great if there was an "official" version of this protocol -- it would save a lot of guesswork. It would be great if you could try it out and report any issues.
