### ISSUE TITLE
Audio delayed with new IOS12 with youtube app [fixed -- updated for iOS12/macOSMojave]

### ISSUE THREAD

**Issue by artenverho** [mikebrady/shairport-sync#747]
Hi Mike,

I seem to have sync issues since I updated both my iPad and iPhone to IOS12 when using youtube. I am running the latest stable version of shairport-sync.

Did you see this as well?

verbose mode does not show any clues (at least not to me):

```
alsa output device name is "default".
Version: "3.2.1-OpenSSL-Avahi-ALSA-soxr-metadata-sysconfdir:/etc"
statistics_requester status is 0.
daemon status is 0.
deamon pid file path is "/var/run/shairport-sync/shairport-sync.pid".
rtsp listening port is 5000.
udp base port is 6001.
udp port range is 100.
player name is "Marantz".
backend is "(null)".
on-start action is "(null)".
on-stop action is "(null)".
wait-cmd status is 0.
on-start returns output is 0.
mdns backend "(null)".
stuffing option is "0" (0-basic, 1-soxr).
resync time is 0.050000 seconds.
allow a session to be interrupted: 0.
busy timeout time is 120.
drift tolerance is 0.001995 seconds.
password is "(null)".
ignore_volume_control is 0.
volume_max_db is not set
playback_mode is 0 (0-stereo, 1-mono, 1-reverse_stereo, 2-both_left, 3-both_right).
disable_synchronization is 0.
use_mmap_if_available is 1.
output_rate is 44100.
output_format is 3 (0-unknown, 1-S8, 2-U8, 3-S16, 4-S24, 5-S24_3LE, 6-S24_3BE, 7-S32).
audio backend desired buffer length is 0.150000 seconds.
audio backend latency offset is 0.000000 seconds.
audio backend silence lead-in time is -1.000000 seconds. A value -1.0 means use the default.
volume range in dB (zero means use the range specified by the mixer): 0.
zeroconf regtype is "_raop._tcp".
decoders_supported field is 3.
use_apple_decoder is 1.
alsa_use_hardware_mute is 0.
no special mdns service interface was requested.
configuration file name "/etc/shairport-sync.conf" resolves to "/etc/shairport-sync.conf".
metadata enabled is 1.
metadata pipename is "/tmp/shairport-sync-metadata".
metadata socket address is "127.0.0.1" port 5555.
metadata socket packet size is "500".
get-coverart is 0.
loudness is 0.
loudness reference level is -20.000000
disable resend requests is off.
diagnostic_drop_packet_fraction is 0.000000. A value of 0.0 means no packets will be dropped deliberately.
avahi: service '0169D78EB23A@Marantz' successfully added.
Dithering will be enabled because the output volume is being altered in software 
```

**Comment by mikebrady** [comment]
Thanks for the post. I haven't noticed a change, to be honest. What kind of a device are you outputting to? Does it by any chance have a digital audio processor in it (that might introduce a slight delay)?

**Comment by mikebrady** [comment]
Yes, I'm noticing a change in Mac Os Mojave. I'll check further...

**Comment by mikebrady** [comment]
Hi there. I've just pushed an update in the `development` branch and I'd be obliged if you would try it out please. It seems to work fine for me.

**Comment by mikebrady** [comment]
Can't help thinking it's still a bit "floaty". I might experiment a little further, but I'd be glad of feedback.

**Comment by FnasBas** [comment]
Hi Mike,

I'd have to say this is not completely resolved. Upgrading to the fixed release version made video sync up from both iOS 12 and Mac OS Mojave. But it's not flawless. Watching a youtube video in safari trough air play, it stutters, gets out of sync, tries to resync and so on. I doesn't happen all the time but often enough to be quite annoying.

Playing to the same shairport server from (high) Sierra I have no issues. I also get no issues when playing audio only content (podcasts) from an ios12 iPhone.

If I can do anything to help and provide debugging info or testing, please let me know what you need.

**Comment by FnasBas** [comment]
I set out to do some testing to see if I could find any patterns. However, now it's not reproducible. I'm still on the same boot on my macbook, same network, same location in the house etc as before. 

I'll get back to you if I can get some consistent problems. It was a bit beyond acceptable before, and now it's completely smooth for some reason..

**Comment by mikebrady** [comment]
Thanks -- I appreciate your support.

**Comment by artenverho** [comment]
Hi mike,

Sorry for my late reply. Too busy these days..
The latest version fixed it! Thanks a lot! Overall this version seems more reliable with ios12.

Cheers,

Arten

**Comment by mikebrady** [comment]
Thanks for the update.
